import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';

/// List of categories of emojis
const List<CategoryEmoji> defaultEmojiSet = [
// ======================================================= Category.SMILEYS
  CategoryEmoji(Category.SMILEYS, [
    Emoji('😀', 'Grinning Face', "U+1F600"),
    Emoji('😁', 'Grinning Face With Big Eyes', "U+1F603"),
    Emoji('😃', 'Grinning Face With Smiling Eyes', "U+1F604"),
    Emoji('😄', 'Beaming Face With Smiling Eyes', "U+1F601"),
    Emoji('😆', 'Grinning Squinting Face', "U+1F606"),
    Emoji('😅', 'Grinning Face With Sweat', "U+1F605"),
    Emoji('🤣', 'Rolling on the Floor Laughing', "U+1F923"),
    Emoji('😂', 'Face With Tears of Joy', "U+1F602"),
    Emoji('🙂', 'Slightly Smiling Face', "U+1F642"),
    Emoji('🙃', 'Upside-Down Face', "U+1F643"),
    Emoji('😉', 'Winking Face', "U+1F609"),
    Emoji('😊', 'Smiling Face With Smiling Eyes', "U+1F60A"),
    Emoji('😇', 'Smiling Face With Halo', "U+1F607"),
    Emoji('🥰', 'Smiling Face With Hearts', "U+1F970"),
    Emoji('😍', 'Smiling Face With Heart-Eyes', "U+1F60D"),
    Emoji('🤩', 'Star-Struck', "U+1F929"),
    Emoji('😘', 'Face Blowing a Kiss', "U+1F618"),
    Emoji('😏', 'Smirking Face', "U+1F60F"),
    Emoji('😋', 'Face Savoring Food', "U+1F60B"),
    Emoji('😛', 'Face With Tongue', "U+1F61B"),
    Emoji('😜', 'Winking Face With Tongue', "U+1F61C"),
    Emoji('🤪', 'Zany Face', "U+1F92A"),
    Emoji('😝', 'Squinting Face With Tongue', "U+1F61D"),
    Emoji('🤑', 'Money-Mouth Face', "U+1F911"),
    Emoji('🤗', 'Hugging Face', "U+1F917"),
    Emoji('🫣', 'Face with Peeking Eye', "U+1F92B"),
    Emoji('🤭', 'Face With Hand Over Mouth', "U+1F92D"),
    Emoji('😮', 'Face with Open Eyes and Hand Over Mouth', "U+1F62E"),
    Emoji('🫡', 'Saluting Face', "U+1F913"),
    Emoji('🤫', 'Shushing Face', "U+1F92B"),
    Emoji('🥵', 'Melting Face', "U+1F976"),
    Emoji('🤔', 'Thinking Face', "U+1F914"),
    Emoji('🤐', 'Zipper-Mouth Face', "U+1F912"),
    Emoji('🤨', 'Face With Raised Eyebrow', "U+1F928"),
    Emoji('😐', 'Neutral Face', "U+1F610"),
    Emoji('😑', 'Face with Diagonal Mouth', "U+1F611"),
    Emoji('😶', 'Expressionless Face', "U+1F636"),
    Emoji('😶‍🌫️', 'Face Without Mouth', "U+1F636 U+200D U+1F32B"),
    Emoji('🥸', 'Dotted Line Face', "U+1F913"),
    Emoji('😏', 'Smirking Face', "U+1F60F"),
    Emoji('😒', 'Unamused Face', "U+1F612"),
    Emoji('🙄', 'Face With Rolling Eyes', "U+1F644"),
    Emoji('😬', 'Grimacing Face', "U+1F62C"),
    Emoji('🤥', 'Lying Face', "U+1F925"),
    Emoji('😌', 'Relieved Face', "U+1F60C"),
    Emoji('😔', 'Pensive Face', "U+1F614"),
    Emoji('😢', 'Face Holding Back Tears', "U+1F622"),
    Emoji('😪', 'Sleepy Face', "U+1F62A"),
    Emoji('🤤', 'Drooling Face', "U+1F924"),
    Emoji('😴', 'Sleeping Face', "U+1F634"),
    Emoji('😷', 'Face With Medical Mask', "U+1F637"),
    Emoji('🤒', 'Face With Thermometer', "U+1F912"),
    Emoji('🤕', 'Face With Head-Bandage', "U+1F915"),
    Emoji('🤢', 'Nauseated Face', "U+1F922"),
    Emoji('🤮', 'Face Vomiting', "U+1F92E"),
    Emoji('🤧', 'Sneezing Face', "U+1F927"),
    Emoji('🥵', 'Hot Face', "U+1F975"),
    Emoji('🥶', 'Cold Face', "U+1F976"),
    Emoji('🥴', 'Woozy Face', "U+1F974"),
    Emoji('😵', 'Dizzy Face', "U+1F635"),
    Emoji('🤯', 'Exploding Head', "U+1F92F"),
    Emoji('🤠', 'Cowboy Hat Face', "U+1F920"),
    Emoji('🥳', 'Partying Face', "U+1F973"),
    Emoji('😎', 'Smiling Face With Sunglasses', "U+1F60E"),
    Emoji('🤓', 'Nerd Face', "U+1F913"),
    Emoji('🧐', 'Face With Monocle', "U+1F9D0"),
    Emoji('😕', 'Confused Face', "U+1F615"),
    Emoji('😟', 'Worried Face', "U+1F61F"),
    Emoji('🙁', 'Slightly Frowning Face', "U+1F641"),
    Emoji('☹️', 'Frowning Face', "U+2639"),
    Emoji('😮', 'Face With Open Mouth', "U+1F62E"),
    Emoji('🤫', 'Hushed Face', "U+1F92B"),
    Emoji('😲', 'Astonished Face', "U+1F632"),
    Emoji('😳', 'Flushed Face', "U+1F633"),
    Emoji('🥺', 'Pleading Face', "U+1F97A"),
    Emoji('😦', 'Frowning Face With Open Mouth', "U+1F626"),
    Emoji('😧', 'Anguished Face', "U+1F627"),
    Emoji('😨', 'Fearful Face', "U+1F628"),
    Emoji('😰', 'Anxious Face With Sweat', "U+1F630"),
    Emoji('😥', 'Sad but Relieved Face', "U+1F625"),
    Emoji('😢', 'Crying Face', "U+1F622"),
    Emoji('😭', 'Loudly Crying Face', "U+1F62D"),
    Emoji('😱', 'Face Screaming in Fear', "U+1F631"),
    Emoji('😖', 'Confounded Face', "U+1F616"),
    Emoji('😣', 'Persevering Face', "U+1F613"),
    Emoji('😞', 'Disappointed Face', "U+1F61E"),
    Emoji('😓', 'Downcast Face With Sweat', "U+1F613"),
    Emoji('😩', 'Weary Face', "U+1F629"),
    Emoji('🥱', 'Tired Face', "U+1F62B"),
    Emoji('😤', 'Face With Steam From Nose', "U+1F624"),
    Emoji('😡', 'Pouting Face', "U+1F621"),
    Emoji('😠', 'Angry Face', "U+1F620"),
    Emoji('🤬', 'Face With Symbols on Mouth', "U+1F92C"),
    Emoji('😈', 'Smiling Face With Horns', "U+1F608"),
    Emoji('😈', 'Angry Face With Horns', "U+1F608"),
    Emoji('💀', 'Skull', "U+1F480"),
    Emoji('☠️', 'Skull and Crossbones', "U+2620"),
    Emoji('💩', 'Pile of Poo', "U+1F4A9"),
    Emoji('🤡', 'Clown Face', "U+1F921"),
    Emoji('👹', 'Ogre', "U+1F479"),
    Emoji('👺', 'Goblin', "U+1F47A"),
    Emoji('👻', 'Ghost', "U+1F47B"),
    Emoji('👽', 'Alien', "U+1F47D"),
    Emoji('👾', 'Alien Monster', "U+1F47E"),
    Emoji('🤖', 'Robot Face', "U+1F916"),
    Emoji('🎃', 'Jack-O-Lantern', "U+1F383"),
    Emoji('😸', 'Grinning Cat Face', "U+1F638"),
    Emoji('😺', 'Grinning Cat Face With Smiling Eyes', "U+1F63A"),
    Emoji('😹', 'Cat Face With Tears of Joy', "U+1F639"),
    Emoji('😻', 'Smiling Cat Face With Heart-Eyes', "U+1F63B"),
    Emoji('😼', 'Cat Face With Wry Smile', "U+1F63C"),
    Emoji('😽', 'Kissing Cat Face', "U+1F63D"),
    Emoji('😿', 'Weary Cat Face', "U+1F63F"),
    Emoji('😿', 'Crying Cat Face', "U+1F640"),
    Emoji('😾', 'Pouting Cat Face', "U+1F63E"),
    Emoji('🫶', 'Heart Hands', "U+1F91F", hasSkinTone: true),
    Emoji('👋', 'Waving Hand', "U+1F44B", hasSkinTone: true),
    Emoji('🤚', 'Raised Back of Hand', "U+1F91A", hasSkinTone: true),
    Emoji('🖐️', 'Hand With Fingers Splayed', "U+1F590", hasSkinTone: true),
    Emoji('✋', 'Raised Hand', "U+270B", hasSkinTone: true),
    Emoji('🖖', 'Vulcan Salute', "U+1F596", hasSkinTone: true),
    Emoji('👌', 'OK Hand', "U+1F44C", hasSkinTone: true),
    Emoji('🤌', 'Pinched Fingers', "U+1F90C", hasSkinTone: true),
    Emoji('🤏', 'Pinching Hand', "U+1F90F", hasSkinTone: true),
    Emoji('👇', 'Palm Down Hand', "U+1F447", hasSkinTone: true),
    Emoji('👆', 'Palm Up Hand', "U+1F446", hasSkinTone: true),
    Emoji('✌️', 'Victory Hand', "U+270C", hasSkinTone: true),
    Emoji('🤞', 'Hand with Index Finger and Thumb Crossed', "U+1F91E",
        hasSkinTone: true),
    Emoji('🤞', 'Crossed Fingers', "U+1F91E", hasSkinTone: true),
    Emoji('🤟', 'Love-You Gesture', "U+1F91F", hasSkinTone: true),
    Emoji('🤘', 'Sign of the Horns', "U+1F918", hasSkinTone: true),
    Emoji('🤙', 'Call Me Hand', "U+1F919", hasSkinTone: true),
    Emoji('👈', 'Backhand Index Pointing Left', "U+1F448", hasSkinTone: true),
    Emoji('👉', 'Backhand Index Pointing Right', "U+1F449", hasSkinTone: true),
    Emoji('👆', 'Backhand Index Pointing Up', "U+1F446", hasSkinTone: true),
    Emoji('🖕', 'Middle Finger', "U+1F595", hasSkinTone: true),
    Emoji('👇', 'Backhand Index Pointing Down', "U+1F447", hasSkinTone: true),
    Emoji('☝️', 'Index Pointing Up', "U+261D", hasSkinTone: true),
    Emoji('👍', 'Thumbs Up', "U+1F44D", hasSkinTone: true),
    Emoji('👎', 'Thumbs Down', "U+1F44E", hasSkinTone: true),
    Emoji('✊', 'Raised Fist', "U+270A", hasSkinTone: true),
    Emoji('👊', 'Oncoming Fist', "U+1F44A", hasSkinTone: true),
    Emoji('🤛', 'Left-Facing Fist', "U+1F91B", hasSkinTone: true),
    Emoji('🤜', 'Right-Facing Fist', "U+1F91C", hasSkinTone: true),
    Emoji('🫲', 'Leftwards Hand', "U+1F91B", hasSkinTone: true),
    Emoji('🫱', 'Rightwards Hand', "U+1F91A", hasSkinTone: true),
    Emoji('👏', 'Clapping Hands', "U+1F44F", hasSkinTone: true),
    Emoji('🙌', 'Raising Hands', "U+1F64C", hasSkinTone: true),
    Emoji('👐', 'Open Hands', "U+1F450", hasSkinTone: true),
    Emoji('🤲', 'Palms Up Together', "U+1F932", hasSkinTone: true),
    Emoji('🤝', 'Handshake', "U+1F91D", hasSkinTone: true),
    Emoji('🙏', 'Folded Hands', "U+1F64F", hasSkinTone: true),
    Emoji('🫵', 'Index Pointing at the Viewer', "U+1F91B", hasSkinTone: true),
    Emoji('✍️', 'Writing Hand', "U+270D", hasSkinTone: true),
    Emoji('💅', 'Nail Polish', "U+1F485", hasSkinTone: true),
    Emoji('🤳', 'Selfie', "U+1F933", hasSkinTone: true),
    Emoji('💪', 'Flexed Biceps', "U+1F4AA", hasSkinTone: true),
    Emoji('🦵', 'Leg', "U+1F9B5", hasSkinTone: true),
    Emoji('🦶', 'Foot', "U+1F9B6", hasSkinTone: true),
    Emoji('👂', 'Ear', "U+1F442", hasSkinTone: true),
    Emoji('👃', 'Nose', "U+1F443", hasSkinTone: true),
    Emoji('🧠', 'Brain', "U+1F9E0"),
    Emoji('🦴', 'Bone', "U+1F9B4"),
    Emoji('👀', 'Eyes', "U+1F440"),
    Emoji('👁️', 'Eye', "U+1F441"),
    Emoji('💋', 'Kiss Mark', "U+1F48B"),
    Emoji('👄', 'Mouth', "U+1F444"),
    Emoji('🫦', 'Biting Lip', "U+1F926"),
    Emoji('🦷', 'Tooth', "U+1F9B7"),
    Emoji('👅', 'Tongue', "U+1F445"),
    Emoji('👶', 'Baby', "U+1F476", hasSkinTone: true),
    Emoji('🧒', 'Child', "U+1F9D2", hasSkinTone: true),
    Emoji('👦', 'Boy', "U+1F466", hasSkinTone: true),
    Emoji('👧', 'Girl', "U+1F467", hasSkinTone: true),
    Emoji('🧑', 'Person', "U+1F9D1", hasSkinTone: true),
    Emoji('👨', 'Man', "U+1F468", hasSkinTone: true),
    Emoji('🧔', 'Man: Beard', "U+1F9B4", hasSkinTone: true),
    Emoji('👱', 'Man: Blond Hair', "U+1F471", hasSkinTone: true),
    Emoji('👨‍🦰', 'Man: Red Hair', "U+1F468 U+1F9B0", hasSkinTone: true),
    Emoji('👨‍🦱', 'Man: Curly Hair', "U+1F468 U+1F9B1", hasSkinTone: true),
    Emoji('👨‍🦳', 'Man: White Hair', "U+1F468 U+1F9B3", hasSkinTone: true),
    Emoji('👨‍🦲', 'Man: Bald', "U+1F468 U+1F9B2", hasSkinTone: true),
    Emoji('👩', 'Woman', "U+1F469", hasSkinTone: true),
    Emoji('👱‍♀️', 'Woman: Blond Hair', "U+1F471 U+200D U+1F469",
        hasSkinTone: true),
    Emoji('👩‍🦰', 'Woman: Red Hair', "U+1F469 U+1F9B0", hasSkinTone: true),
    Emoji('👩‍🦱', 'Woman: Curly Hair', "U+1F469 U+1F9B1", hasSkinTone: true),
    Emoji('👩‍🦳', 'Woman: White Hair', "U+1F469 U+1F9B3", hasSkinTone: true),
    Emoji('👩‍🦲', 'Woman: Bald', "U+1F469 U+1F9B2", hasSkinTone: true),
    Emoji('🧓', 'Older Person', "U+1F9D3", hasSkinTone: true),
    Emoji('👴', 'Old Man', "U+1F474", hasSkinTone: true),
    Emoji('👵', 'Old Woman', "U+1F475", hasSkinTone: true),
    Emoji('🙍‍♂️', 'Man Frowning', "U+1F64D U+200D U+2642", hasSkinTone: true),
    Emoji('🙍‍♀️', 'Woman Frowning', "U+1F64D U+200D U+2640",
        hasSkinTone: true),
    Emoji('🙎‍♂️', 'Man Pouting', "U+1F64E U+200D U+2642", hasSkinTone: true),
    Emoji('🙎‍♀️', 'Woman Pouting', "U+1F64E U+200D U+2640", hasSkinTone: true),
    Emoji('🙅‍♂️', 'Man Gesturing No', "U+1F645 U+200D U+2642",
        hasSkinTone: true),
    Emoji('🙅‍♀️', 'Woman Gesturing No', "U+1F645 U+200D U+2640",
        hasSkinTone: true),
    Emoji('🙆‍♂️', 'Man Gesturing OK', "U+1F646 U+200D U+2642",
        hasSkinTone: true),
    Emoji('🙆‍♀️', 'Woman Gesturing OK', "U+1F646 U+200D U+2640",
        hasSkinTone: true),
    Emoji('💁‍♂️', 'Man Tipping Hand', "U+1F481 U+200D U+2642",
        hasSkinTone: true),
    Emoji('💁‍♀️', 'Woman Tipping Hand', "U+1F481 U+200D U+2640",
        hasSkinTone: true),
    Emoji('🙋‍♂️', 'Man Raising Hand', "U+1F64B U+200D U+2642",
        hasSkinTone: true),
    Emoji('🙋‍♀️', 'Woman Raising Hand', "U+1F64B U+200D U+2640",
        hasSkinTone: true),
    Emoji('🙇‍♂️', 'Man Bowing', "U+1F647 U+200D U+2642", hasSkinTone: true),
    Emoji('🙇‍♀️', 'Woman Bowing', "U+1F647 U+200D U+2640", hasSkinTone: true),
    Emoji('🤦‍♂️', 'Man Facepalming', "U+1F926 U+200D U+2642",
        hasSkinTone: true),
    Emoji('🤦‍♀️', 'Woman Facepalming', "U+1F926 U+200D U+2640",
        hasSkinTone: true),
    Emoji('🤷‍♂️', 'Man Shrugging', "U+1F937 U+200D U+2642", hasSkinTone: true),
    Emoji('🤷‍♀️', 'Woman Shrugging', "U+1F937 U+200D U+2640",
        hasSkinTone: true),
    Emoji('👨‍⚕️', 'Man Health Worker', "U+1F468 U+200D U+2695",
        hasSkinTone: true),
    Emoji('👩‍⚕️', 'Woman Health Worker', "U+1F469 U+200D U+2695",
        hasSkinTone: true),
    Emoji('👨‍🎓', 'Man Student', "U+1F468 U+200D U+1F393", hasSkinTone: true),
    Emoji('👩‍🎓', 'Woman Student', "U+1F469 U+200D U+1F393",
        hasSkinTone: true),
    Emoji('👨‍🏫', 'Man Teacher', "U+1F468 U+200D U+1F3EB", hasSkinTone: true),
    Emoji('👩‍🏫', 'Woman Teacher', "U+1F469 U+200D U+1F3EB",
        hasSkinTone: true),
    Emoji('👨‍⚖️', 'Man Judge', "U+1F468 U+200D U+2696", hasSkinTone: true),
    Emoji('👩‍⚖️', 'Woman Judge', "U+1F469 U+200D U+2696", hasSkinTone: true),
    Emoji('👨‍🌾', 'Man Farmer', "U+1F468 U+200D U+1F33E", hasSkinTone: true),
    Emoji('👩‍🌾', 'Woman Farmer', "U+1F469 U+200D U+1F33E", hasSkinTone: true),
    Emoji('👨‍🍳', 'Man Cook', "U+1F468 U+200D U+1F373", hasSkinTone: true),
    Emoji('👩‍🍳', 'Woman Cook', "U+1F469 U+200D U+1F373", hasSkinTone: true),
    Emoji('👨‍🔧', 'Man Mechanic', "U+1F468 U+200D U+1F527", hasSkinTone: true),
    Emoji('👩‍🔧', 'Woman Mechanic', "U+1F469 U+200D U+1F527",
        hasSkinTone: true),
    Emoji('👨‍🏭', 'Man Factory Worker', "U+1F468 U+200D U+1F3ED",
        hasSkinTone: true),
    Emoji('👩‍🏭', 'Woman Factory Worker', "U+1F469 U+200D U+1F3ED",
        hasSkinTone: true),
    Emoji('👨‍💼', 'Man Office Worker', "U+1F468 U+200D U+1F4BC",
        hasSkinTone: true),
    Emoji('👩‍💼', 'Woman Office Worker', "U+1F469 U+200D U+1F4BC",
        hasSkinTone: true),
    Emoji('👨‍🔬', 'Man Scientist', "U+1F468 U+200D U+1F52C",
        hasSkinTone: true),
    Emoji('👩‍🔬', 'Woman Scientist', "U+1F469 U+200D U+1F52C",
        hasSkinTone: true),
    Emoji('👨‍💻', 'Man Technologist', "U+1F468 U+200D U+1F4BB",
        hasSkinTone: true),
    Emoji('👩‍💻', 'Woman Technologist', "U+1F469 U+200D U+1F4BB",
        hasSkinTone: true),
    Emoji('👨‍🎤', 'Man Singer', "U+1F468 U+200D U+1F3A4", hasSkinTone: true),
    Emoji('👩‍🎤', 'Woman Singer', "U+1F469 U+200D U+1F3A4", hasSkinTone: true),
    Emoji('👨‍🎨', 'Man Artist', "U+1F468 U+200D U+1F3A8", hasSkinTone: true),
    Emoji('👩‍🎨', 'Woman Artist', "U+1F469 U+200D U+1F3A8", hasSkinTone: true),
    Emoji('👨‍✈️', 'Man Pilot', "U+1F468 U+200D U+2708", hasSkinTone: true),
    Emoji('👩‍✈️', 'Woman Pilot', "U+1F469 U+200D U+2708", hasSkinTone: true),
    Emoji('👨‍🚀', 'Man Astronaut', "U+1F468 U+200D U+1F680",
        hasSkinTone: true),
    Emoji('👩‍🚀', 'Woman Astronaut', "U+1F469 U+200D U+1F680",
        hasSkinTone: true),
    Emoji('👨‍🚒', 'Man Firefighter', "U+1F468 U+200D U+1F692",
        hasSkinTone: true),
    Emoji('👩‍🚒', 'Woman Firefighter', "U+1F469 U+200D U+1F692",
        hasSkinTone: true),
    Emoji('👮‍♂️', 'Man Police Officer', "U+1F46E U+200D U+2642",
        hasSkinTone: true),
    Emoji('👮‍♀️', 'Woman Police Officer', "U+1F46E U+200D U+2640",
        hasSkinTone: true),
    Emoji('🕵️‍♂️', 'Man Detective', "U+1F575 U+200D U+2642",
        hasSkinTone: true),
    Emoji('🕵️‍♀️', 'Woman Detective', "U+1F575 U+200D U+2640",
        hasSkinTone: true),
    Emoji('💂‍♂️', 'Man Guard', "U+1F482 U+200D U+2642", hasSkinTone: true),
    Emoji('💂‍♀️', 'Woman Guard', "U+1F482 U+200D U+2640", hasSkinTone: true),
    Emoji('👷‍♂️', 'Man Construction Worker', "U+1F477 U+200D U+2642",
        hasSkinTone: true),
    Emoji('👷‍♀️', 'Woman Construction Worker', "U+1F477 U+200D U+2640",
        hasSkinTone: true),
    Emoji('🤴', 'Prince', "U+1F934", hasSkinTone: true),
    Emoji('👸', 'Princess', "U+1F478", hasSkinTone: true),
    Emoji('👳‍♂️', 'Man Wearing Turban', "U+1F472", hasSkinTone: true),
    Emoji('👳‍♀️', 'Woman Wearing Turban', "U+1F473", hasSkinTone: true),
    Emoji('👲', 'Man With Chinese Cap', "U+1F472"),
    Emoji('🧕', 'Woman With Headscarf', "U+1F9D5"),
    Emoji('🤵', 'Man in Tuxedo', "U+1F935", hasSkinTone: true),
    Emoji('👰', 'Bride With Veil', "U+1F470", hasSkinTone: true),
    Emoji('🤰', 'Pregnant Woman', "U+1F930", hasSkinTone: true),
    Emoji('🤱', 'Breast-Feeding', "U+1F931", hasSkinTone: true),
    Emoji('👼', 'Baby Angel', "U+1F47C", hasSkinTone: true),
    Emoji('🎅', 'Santa Claus', "U+1F385", hasSkinTone: true),
    Emoji('🤶', 'Mrs. Claus', "U+1F936", hasSkinTone: true),
    Emoji('🦸‍♂️', 'Man Superhero', "U+1F9B8 U+200D U+2642", hasSkinTone: true),
    Emoji('🦸‍♀️', 'Woman Superhero', "U+1F9B8 U+200D U+2640",
        hasSkinTone: true),
    Emoji('🦹‍♂️', 'Man Supervillain', "U+1F9B9 U+200D U+2642",
        hasSkinTone: true),
    Emoji('🦹‍♀️', 'Woman Supervillain', "U+1F9B9 U+200D U+2640",
        hasSkinTone: true),
    Emoji('🧙‍♂️', 'Man Mage', "U+1F9D9 U+200D U+2642", hasSkinTone: true),
    Emoji('🧙‍♀️', 'Woman Mage', "U+1F9D9 U+200D U+2640", hasSkinTone: true),
    Emoji('🧚‍♂️', 'Man Fairy', "U+1F9DA U+200D U+2642", hasSkinTone: true),
    Emoji('🧚‍♀️', 'Woman Fairy', "U+1F9DA U+200D U+2640", hasSkinTone: true),
    Emoji('🧛‍♂️', 'Man Vampire', "U+1F9DB U+200D U+2642", hasSkinTone: true),
    Emoji('🧛‍♀️', 'Woman Vampire', "U+1F9DB U+200D U+2640", hasSkinTone: true),
    Emoji('🧜‍♂️', 'Merman', "U+1F9DC U+200D U+2642", hasSkinTone: true),
    Emoji('🧜‍♀️', 'Mermaid', "U+1F9DC U+200D U+2640", hasSkinTone: true),
    Emoji('🧝‍♂️', 'Man Elf', "U+1F9DD U+200D U+2642", hasSkinTone: true),
    Emoji('🧝‍♀️', 'Woman Elf', "U+1F9DD U+200D U+2640", hasSkinTone: true),
    Emoji('🧞‍♂️', 'Man Genie', "U+1F9DE U+200D U+2642"),
    Emoji('🧞‍♀️', 'Woman Genie', "U+1F9DE U+200D U+2640"),
    Emoji('🧟‍♂️', 'Man Zombie', "U+1F9DF U+200D U+2642"),
    Emoji('🧟‍♀️', 'Woman Zombie', "U+1F9DF U+200D U+2640"),
    Emoji('💆‍♂️', 'Man Getting Massage', "U+1F486 U+200D U+2642",
        hasSkinTone: true),
    Emoji('💆‍♀️', 'Woman Getting Massage', "U+1F486 U+200D U+2640",
        hasSkinTone: true),
    Emoji('💇‍♂️', 'Man Getting Haircut', "U+1F487 U+200D U+2642",
        hasSkinTone: true),
    Emoji('💇‍♀️', 'Woman Getting Haircut', "U+1F487 U+200D U+2640",
        hasSkinTone: true),
    Emoji('🚶‍♂️', 'Man Walking', "U+1F6B6 U+200D U+2642", hasSkinTone: true),
    Emoji('🚶‍♀️', 'Woman Walking', "U+1F6B6 U+200D U+2640", hasSkinTone: true),
    Emoji('🏃‍♂️', 'Man Running', "U+1F3C3 U+200D U+2642", hasSkinTone: true),
    Emoji('🏃‍♀️', 'Woman Running', "U+1F3C3 U+200D U+2640", hasSkinTone: true),
    Emoji('🕺', 'Man Dancing', "U+1F57A", hasSkinTone: true),
    Emoji('💃', 'Woman Dancing', "U+1F483", hasSkinTone: true),
    Emoji('🕴️', 'Man in Suit Levitating', "U+1F574", hasSkinTone: true),
    Emoji('👯‍♂️', 'Men With Bunny Ears', "U+1F46F U+200D U+2642"),
    Emoji('👯‍♀️', 'Women With Bunny Ears', "U+1F46F U+200D U+2640"),
    Emoji('🧖‍♂️', 'Man in Steamy Room', "U+1F9D6 U+200D U+2642",
        hasSkinTone: true),
    Emoji('🧖‍♀️', 'Woman in Steamy Room', "U+1F9D6 U+200D U+2640",
        hasSkinTone: true),
    Emoji('🧘', 'Person in Lotus Position', "U+1F9D8", hasSkinTone: true),
    Emoji('👭', 'Women Holding Hands', "U+1F46D", hasSkinTone: true),
    Emoji('👫', 'Woman and Man Holding Hands', "U+1F46B", hasSkinTone: true),
    Emoji('👬', 'Men Holding Hands', "U+1F46C", hasSkinTone: true),
    Emoji('💏', 'Kiss', "U+1F48F"),
    Emoji('👨‍❤️‍💋‍👨', 'Kiss: Man, Man',
        "U+1F468 U+200D U+2764 U+FE0F U+1F48F"),
    Emoji('👩‍❤️‍💋‍👩', 'Kiss: Woman, Woman',
        "U+1F469 U+200D U+2764 U+FE0F U+1F48F"),
    Emoji('💑', 'Couple With Heart', "U+1F491"),
    Emoji('👨‍❤️‍👨', 'Couple With Heart: Man, Man',
        "U+1F468 U+200D U+2764 U+FE0F U+1F468"),
    Emoji('👩‍❤️‍👩', 'Couple With Heart: Woman, Woman',
        "U+1F469 U+200D U+2764 U+FE0F U+1F469"),
    Emoji('👪', 'Family', "U+1F46A"),
    Emoji('👨‍👩‍👦', 'Family: Man, Woman, Boy',
        "U+1F468 U+200D U+1F469 U+200D U+1F466"),
    Emoji('👨‍👩‍👧', 'Family: Man, Woman, Girl',
        "U+1F468 U+200D U+1F469 U+200D U+1F467"),
    Emoji('👨‍👩‍👧‍👦', 'Family: Man, Woman, Girl, Boy',
        "U+1F468 U+200D U+1F469 U+200D U+1F467 U+200D U+1F466"),
    Emoji('👨‍👩‍👦‍👦', 'Family: Man, Woman, Boy, Boy',
        "U+1F468 U+200D U+1F469 U+200D U+1F466 U+200D U+1F466"),
    Emoji('👨‍👩‍👧‍👧', 'Family: Man, Woman, Girl, Girl',
        "U+1F468 U+200D U+1F469 U+200D U+1F467 U+200D U+1F467"),
    Emoji('👨‍👨‍👦', 'Family: Man, Man, Boy',
        "U+1F468 U+200D U+1F468 U+200D U+1F466"),
    Emoji('👨‍👨‍👧', 'Family: Man, Man, Girl',
        "U+1F468 U+200D U+1F468 U+200D U+1F467"),
    Emoji('👨‍👨‍👧‍👦', 'Family: Man, Man, Girl, Boy',
        "U+1F468 U+200D U+1F468 U+200D U+1F467 U+200D U+1F466"),
    Emoji('👨‍👨‍👦‍👦', 'Family: Man, Man, Boy, Boy',
        "U+1F468 U+200D U+1F468 U+200D U+1F466 U+200D U+1F466"),
    Emoji('👨‍👨‍👧‍👧', 'Family: Man, Man, Girl, Girl',
        "U+1F468 U+200D U+1F468 U+200D U+1F467 U+200D U+1F467"),
    Emoji('👩‍👩‍👦', 'Family: Woman, Woman, Boy',
        "U+1F469 U+200D U+1F469 U+200D U+1F466"),
    Emoji('👩‍👩‍👧', 'Family: Woman, Woman, Girl',
        "U+1F469 U+200D U+1F469 U+200D U+1F467"),
    Emoji('👩‍👩‍👧‍👦', 'Family: Woman, Woman, Girl, Boy',
        "U+1F469 U+200D U+1F469 U+200D U+1F467 U+200D U+1F466"),
    Emoji('👩‍👩‍👦‍👦', 'Family: Woman, Woman, Boy, Boy',
        "U+1F469 U+200D U+1F469 U+200D U+1F466 U+200D U+1F466"),
    Emoji('👩‍👩‍👧‍👧', 'Family: Woman, Woman, Girl, Girl',
        "U+1F469 U+200D U+1F469 U+200D U+1F467 U+200D U+1F467"),
    Emoji('👨‍👦', 'Family: Man, Boy', "U+1F468 U+200D U+1F466"),
    Emoji('👨‍👦‍👦', 'Family: Man, Boy, Boy',
        "U+1F468 U+200D U+1F466 U+200D U+1F466"),
    Emoji('👨‍👧', 'Family: Man, Girl', "U+1F468 U+200D U+1F467"),
    Emoji('👨‍👧‍👦', 'Family: Man, Girl, Boy',
        "U+1F468 U+200D U+1F467 U+200D U+1F466"),
    Emoji('👨‍👧‍👧', 'Family: Man, Girl, Girl',
        "U+1F468 U+200D U+1F467 U+200D U+1F467"),
    Emoji('👩‍👦', 'Family: Woman, Boy', "U+1F469 U+200D U+1F466"),
    Emoji('👩‍👦‍👦', 'Family: Woman, Boy, Boy',
        "U+1F469 U+200D U+1F466 U+200D U+1F466"),
    Emoji('👩‍👧', 'Family: Woman, Girl', "U+1F469 U+200D U+1F467"),
    Emoji('👩‍👧‍👦', 'Family: Woman, Girl, Boy',
        "U+1F469 U+200D U+1F467 U+200D U+1F466"),
    Emoji('👩‍👧‍👧', 'Family: Woman, Girl, Girl',
        "U+1F469 U+200D U+1F467 U+200D U+1F467"),
    Emoji('🗣️', 'Speaking Head', "U+1F5E3"),
    Emoji('👤', 'Bust in Silhouette', "U+1F464"),
    Emoji('👥', 'Busts in Silhouette', "U+1F465"),
    Emoji('👣', 'Footprints', "U+1F463"),
    Emoji('🧳', 'Luggage', "U+1F9F3"),
    Emoji('🌂', 'Closed Umbrella', "U+1F302"),
    Emoji('☂️', 'Umbrella', "U+2602"),
    Emoji('🧵', 'Thread', "U+1F9F5"),
    Emoji('🧶', 'Yarn', "U+1F9F6"),
    Emoji('👓', 'Glasses', "U+1F453"),
    Emoji('🕶️', 'Sunglasses', "U+1F576"),
    Emoji('🥽', 'Goggles', "U+1F97D"),
    Emoji('🥼', 'Lab Coat', "U+1F97C"),
    Emoji('👔', 'Necktie', "U+1F454"),
    Emoji('👕', 'T-Shirt', "U+1F455"),
    Emoji('👖', 'Jeans', "U+1F456"),
    Emoji('🧣', 'Scarf', "U+1F9C3"),
    Emoji('🧤', 'Gloves', "U+1F9E4"),
    Emoji('🧥', 'Coat', "U+1F9E5"),
    Emoji('🧦', 'Socks', "U+1F9E6"),
    Emoji('👗', 'Dress', "U+1F457"),
    Emoji('👘', 'Kimono', "U+1F458"),
    Emoji('👙', 'Bikini', "U+1F459"),
    Emoji('👚', 'Woman’s Clothes', "U+1F45A"),
    Emoji('👛', 'Purse', "U+1F45B"),
    Emoji('👜', 'Handbag', "U+1F45C"),
    Emoji('👝', 'Clutch Bag', "U+1F45D"),
    Emoji('🎒', 'Backpack', "U+1F392"),
    Emoji('👞', 'Man’s Shoe', "U+1F45E"),
    Emoji('👟', 'Running Shoe', "U+1F45F"),
    Emoji('🥾', 'Hiking Boot', "U+1F97E"),
    Emoji('🥿', 'Flat Shoe', "U+1F97F"),
    Emoji('👠', 'High-Heeled Shoe', "U+1F460"),
    Emoji('👡', 'Woman’s Sandal', "U+1F461"),
    Emoji('👢', 'Woman’s Boot', "U+1F462"),
    Emoji('👑', 'Crown', "U+1F451"),
    Emoji('👒', 'Woman’s Hat', "U+1F452"),
    Emoji('🎩', 'Top Hat', "U+1F3A9"),
    Emoji('🎓', 'Graduation Cap', "U+1F393"),
    Emoji('🧢', 'Billed Cap', "U+1F9E2"),
    Emoji('⛑️', 'Rescue Worker’s Helmet', "U+26D1"),
    Emoji('💄', 'Lipstick', "U+1F484"),
    Emoji('💍', 'Ring', "U+1F48D"),
    Emoji('💼', 'Briefcase', "U+1F4BC")
  ]),

// ======================================================= Category.ANIMALS
  CategoryEmoji(Category.ANIMALS, [
    Emoji('🐶', 'Dog Face', "U+1F436"),
    Emoji('🐱', 'Cat Face', "U+1F638"),
    Emoji('🐭', 'Mouse Face', "U+1F42D"),
    Emoji('🐹', 'Hamster Face', "U+1F439"),
    Emoji('🐰', 'Rabbit Face', "U+1F430"),
    Emoji('🦊', 'Fox Face', "U+1F98A"),
    Emoji('🐻', 'Bear Face', "U+1F43B"),
    Emoji('🐼', 'Panda Face', "U+1F43C"),
    Emoji('🐨', 'Koala Face', "U+1F428"),
    Emoji('🐯', 'Tiger Face', "U+1F42F"),
    Emoji('🦁', 'Lion Face', "U+1F981"),
    Emoji('🐮', 'Cow Face', "U+1F42E"),
    Emoji('🐷', 'Pig Face', "U+1F437"),
    Emoji('🐽', 'Pig Nose', "U+1F43D"),
    Emoji('🐸', 'Frog Face', "U+1F438"),
    Emoji('🐵', 'Monkey Face', "U+1F435"),
    Emoji('🙈', 'See-No-Evil Monkey', "U+1F648"),
    Emoji('🙉', 'Hear-No-Evil Monkey', "U+1F649"),
    Emoji('🙊', 'Speak-No-Evil Monkey', "U+1F64A"),
    Emoji('🐒', 'Monkey', "U+1F412"),
    Emoji('💥', 'Collision', "U+1F4A5"),
    Emoji('💫', 'Dizzy', "U+1F4AB"),
    Emoji('💦', 'Sweat Droplets', "U+1F4A6"),
    Emoji('💨', 'Dashing Away', "U+1F32B"),
    Emoji('🦍', 'Gorilla', "U+1F98D"),
    Emoji('🐕', 'Dog', "U+1F415"),
    Emoji('🐩', 'Poodle', "U+1F429"),
    Emoji('🐺', 'Wolf Face', "U+1F43A"),
    Emoji('🦝', 'Raccoon', "U+1F99D"),
    Emoji('🐈', 'Cat', "U+1F408"),
    Emoji('🐅', 'Tiger', "U+1F405"),
    Emoji('🐆', 'Leopard', "U+1F406"),
    Emoji('🐴', 'Horse Face', "U+1F434"),
    Emoji('🐎', 'Horse', "U+1F40E"),
    Emoji('🦄', 'Unicorn Face', "U+1F984"),
    Emoji('🦓', 'Zebra', "U+1F993"),
    Emoji('🐂', 'Ox', "U+1F402"),
    Emoji('🐃', 'Water Buffalo', "U+1F403"),
    Emoji('🐄', 'Cow', "U+1F404"),
    Emoji('🐖', 'Pig', "U+1F416"),
    Emoji('🐗', 'Boar', "U+1F417"),
    Emoji('🐏', 'Ram', "U+1F40F"),
    Emoji('🐑', 'Ewe', "U+1F411"),
    Emoji('🐐', 'Goat', "U+1F410"),
    Emoji('🐪', 'Camel', "U+1F42A"),
    Emoji('🐫', 'Two-Hump Camel', "U+1F42B"),
    Emoji('🦙', 'Llama', "U+1F999"),
    Emoji('🦒', 'Giraffe', "U+1F992"),
    Emoji('🐘', 'Elephant', "U+1F418"),
    Emoji('🦏', 'Rhinoceros', "U+1F98F"),
    Emoji('🦛', 'Hippopotamus', "U+1F99B"),
    Emoji('🐁', 'Mouse', "U+1F401"),
    Emoji('🐀', 'Rat', "U+1F400"),
    Emoji('🐇', 'Rabbit', "U+1F407"),
    Emoji('🐿️', 'Chipmunk', "U+1F43F"),
    Emoji('🦔', 'Hedgehog', "U+1F994"),
    Emoji('🦇', 'Bat', "U+1F987"),
    Emoji('🦘', 'Kangaroo', "U+1F998"),
    Emoji('🦡', 'Badger', "U+1F9A1"),
    Emoji('🐾', 'Paw Prints', "U+1F43E"),
    Emoji('🦃', 'Turkey', "U+1F983"),
    Emoji('🐔', 'Chicken', "U+1F414"),
    Emoji('🐓', 'Rooster', "U+1F413"),
    Emoji('🐣', 'Hatching Chick', "U+1F423"),
    Emoji('🐤', 'Baby Chick', "U+1F424"),
    Emoji('🐥', 'Front-Facing Baby Chick', "U+1F425"),
    Emoji('🐦', 'Bird', "U+1F426"),
    Emoji('🐧', 'Penguin', "U+1F427"),
    Emoji('🕊️', 'Dove', "U+1F54A"),
    Emoji('🦅', 'Eagle', "U+1F985"),
    Emoji('🦆', 'Duck', "U+1F986"),
    Emoji('🦢', 'Swan', "U+1F9A2"),
    Emoji('🦉', 'Owl', "U+1F989"),
    Emoji('🦚', 'Peacock', "U+1F99A"),
    Emoji('🦜', 'Parrot', "U+1F99C"),
    Emoji('🐊', 'Crocodile', "U+1F40A"),
    Emoji('🐢', 'Turtle', "U+1F422"),
    Emoji('🦎', 'Lizard', "U+1F98E"),
    Emoji('🐍', 'Snake', "U+1F40D"),
    Emoji('🐲', 'Dragon Face', "U+1F432"),
    Emoji('🐉', 'Dragon', "U+1F409"),
    Emoji('🦕', 'Sauropod', "U+1F995"),
    Emoji('🦖', 'T-Rex', "U+1F996"),
    Emoji('🧌', 'Troll', "U+1F9CC"),
    Emoji('🐳', 'Spouting Whale', "U+1F433"),
    Emoji('🐋', 'Whale', "U+1F40B"),
    Emoji('🐬', 'Dolphin', "U+1F42C"),
    Emoji('🐟', 'Fish', "U+1F41F"),
    Emoji('🐠', 'Tropical Fish', "U+1F420"),
    Emoji('🐡', 'Blowfish', "U+1F421"),
    Emoji('🦈', 'Shark', "U+1F988"),
    Emoji('🐙', 'Octopus', "U+1F419"),
    Emoji('🪹', 'Empty Nest', "U+1FA79"),
    Emoji('🪺', 'Nest with Eggs', "U+1FA7A"),
    Emoji('🐚', 'Spiral Shell', "U+1F41A"),
    Emoji('🪸', 'Coral', "U+1FA78"),
    Emoji('🐌', 'Snail', "U+1F40C"),
    Emoji('🦋', 'Butterfly', "U+1F98B"),
    Emoji('🐛', 'Bug', "U+1F41B"),
    Emoji('🐜', 'Ant', "U+1F41C"),
    Emoji('🐝', 'Honeybee', "U+1F41D"),
    Emoji('🐞', 'Lady Beetle', "U+1F41E"),
    Emoji('🦗', 'Cricket', "U+1F997"),
    Emoji('🕷️', 'Spider', "U+1F577"),
    Emoji('🕸️', 'Spider Web', "U+1F578"),
    Emoji('🦂', 'Scorpion', "U+1F982"),
    Emoji('🦟', 'Mosquito', "U+1F99F"),
    Emoji('🦠', 'Microbe', "U+1F9A0"),
    Emoji('💐', 'Bouquet', "U+1F490"),
    Emoji('🌸', 'Cherry Blossom', "U+1F338"),
    Emoji('💮', 'White Flower', "U+1F4AE"),
    Emoji('🏵️', 'Rosette', "U+1F3F5"),
    Emoji('🪷', 'Lotus', "U+1FA73"),
    Emoji('🌹', 'Rose', "U+1F339"),
    Emoji('🥀', 'Wilted Flower', "U+1F940"),
    Emoji('🌺', 'Hibiscus', "U+1F33A"),
    Emoji('🌻', 'Sunflower', "U+1F33B"),
    Emoji('🌼', 'Blossom', "U+1F33C"),
    Emoji('🌷', 'Tulip', "U+1F337"),
    Emoji('🌱', 'Seedling', "U+1F331"),
    Emoji('🌲', 'Evergreen Tree', "U+1F332"),
    Emoji('🌳', 'Deciduous Tree', "U+1F333"),
    Emoji('🌴', 'Palm Tree', "U+1F334"),
    Emoji('🌵', 'Cactus', "U+1F335"),
    Emoji('🌾', 'Sheaf of Rice', "U+1F33E"),
    Emoji('🌿', 'Herb', "U+1F33F"),
    Emoji('☘️', 'Shamrock', "U+2618"),
    Emoji('🍀', 'Four Leaf Clover', "U+1F340"),
    Emoji('🍁', 'Maple Leaf', "U+1F341"),
    Emoji('🍂', 'Fallen Leaf', "U+1F342"),
    Emoji('🍃', 'Leaf Fluttering in Wind', "U+1F343"),
    Emoji('🍄', 'Mushroom', "U+1F344"),
    Emoji('🌰', 'Chestnut', "U+1F330"),
    Emoji('🦀', 'Crab', "U+1F980"),
    Emoji('🦞', 'Lobster', "U+1F99E"),
    Emoji('🦐', 'Shrimp', "U+1F990"),
    Emoji('🦑', 'Squid', "U+1F991"),
    Emoji('🌍', 'Globe Showing Europe-Africa', "U+1F30D"),
    Emoji('🌎', 'Globe Showing Americas', "U+1F30E"),
    Emoji('🌏', 'Globe Showing Asia-Australia', "U+1F30F"),
    Emoji('🌐', 'Globe With Meridians', "U+1F310"),
    Emoji('🌑', 'New Moon', "U+1F311"),
    Emoji('🌒', 'Waxing Crescent Moon', "U+1F312"),
    Emoji('🌓', 'First Quarter Moon', "U+1F313"),
    Emoji('🌔', 'Waxing Gibbous Moon', "U+1F314"),
    Emoji('🌕', 'Full Moon', "U+1F315"),
    Emoji('🌖', 'Waning Gibbous Moon', "U+1F316"),
    Emoji('🌗', 'Last Quarter Moon', "U+1F317"),
    Emoji('🌘', 'Waning Crescent Moon', "U+1F318"),
    Emoji('🌙', 'Crescent Moon', "U+1F319"),
    Emoji('🌚', 'New Moon Face', "U+1F31A"),
    Emoji('🌛', 'First Quarter Moon Face', "U+1F31B"),
    Emoji('🌜', 'Last Quarter Moon Face', "U+1F31C"),
    Emoji('☀️', 'Sun', "U+2600"),
    Emoji('🌝', 'Full Moon Face', "U+1F92D"),
    Emoji('🌞', 'Sun With Face', "U+1F31E"),
    Emoji('⭐', 'Star', "U+2B50"),
    Emoji('🌟', 'Glowing Star', "U+1F31F"),
    Emoji('🌠', 'Shooting Star', "U+1F320"),
    Emoji('☁️', 'Cloud', "U+2601"),
    Emoji('⛅', 'Sun Behind Cloud', "U+26C8"),
    Emoji('⛈️', 'Cloud With Lightning and Rain', "U+26C8"),
    Emoji('🌤️', 'Sun Behind Small Cloud', "U+1F324"),
    Emoji('🌥️', 'Sun Behind Large Cloud', "U+1F325"),
    Emoji('🌦️', 'Sun Behind Rain Cloud', "U+1F326"),
    Emoji('🌧️', 'Cloud With Rain', "U+1F327"),
    Emoji('🌨️', 'Cloud With Snow', "U+1F328"),
    Emoji('🌩️', 'Cloud With Lightning', "U+1F329"),
    Emoji('🌪️', 'Tornado', "U+1F32A"),
    Emoji('🌫️', 'Fog', "U+1F32B"),
    Emoji('🌬️', 'Wind Face', "U+1F32C"),
    Emoji('🌈', 'Rainbow', "U+1F308"),
    Emoji('☂️', 'Umbrella', "U+2602"),
    Emoji('☔', 'Umbrella With Rain Drops', "U+2614"),
    Emoji('⚡', 'High Voltage', "U+26A1"),
    Emoji('❄️', 'Snowflake', "U+2744"),
    Emoji('☃️', 'Snowman', "U+2603"),
    Emoji('⛄', 'Snowman Without Snow', "U+26C4"),
    Emoji('☄️', 'Comet', "U+2604"),
    Emoji('🔥', 'Fire', "U+1F525"),
    Emoji('💧', 'Droplet', "U+1F4A7"),
    Emoji('🫧', 'Bubbles', "U+1F9CB"),
    Emoji('🌊', 'Water Wave', "U+1F30A"),
    Emoji('🎄', 'Christmas Tree', "U+1F384"),
    Emoji('✨', 'Sparkles', "U+2728"),
    Emoji('🎋', 'Tanabata Tree', "U+1F38B"),
    Emoji('🎍', 'Pine Decoration', "U+1F38D")
  ]),

// ======================================================= Category.FOODS
  CategoryEmoji(Category.FOODS, [
    Emoji('🍇', 'Grapes', "U+1F347"),
    Emoji('🍈', 'Melon', "U+1F348"),
    Emoji('🍉', 'Watermelon', "U+1F349"),
    Emoji('🍊', 'Tangerine', "U+1F34A"),
    Emoji('🍋', 'Lemon', "U+1F34B"),
    Emoji('🍌', 'Banana', "U+1F34C"),
    Emoji('🍍', 'Pineapple', "U+1F350"),
    Emoji('🥭', 'Mango', "U+1F96D"),
    Emoji('🍎', 'Red Apple', "U+1F34E"),
    Emoji('🍏', 'Green Apple', "U+1F34F"),
    Emoji('🍐', 'Pear', "U+1F350"),
    Emoji('🍑', 'Peach', "U+1F351"),
    Emoji('🍒', 'Cherries', "U+1F352"),
    Emoji('🍓', 'Strawberry', "U+1F353"),
    Emoji('🥝', 'Kiwi Fruit', "U+1F95D"),
    Emoji('🍅', 'Tomato', "U+1F345"),
    Emoji('🥥', 'Coconut', "U+1F965"),
    Emoji('🥑', 'Avocado', "U+1F951"),
    Emoji('🍆', 'Eggplant', "U+1F346"),
    Emoji('🥔', 'Potato', "U+1F954"),
    Emoji('🥕', 'Carrot', "U+1F955"),
    Emoji('🌽', 'Ear of Corn', "U+1F33D"),
    Emoji('🌶️', 'Hot Pepper', "U+1F336"),
    Emoji('🥒', 'Cucumber', "U+1F952"),
    Emoji('🥬', 'Leafy Green', "U+1F96C"),
    Emoji('🥦', 'Broccoli', "U+1F966"),
    Emoji('🍄', 'Mushroom', "U+1F344"),
    Emoji('🥜', 'Peanuts', "U+1F95C"),
    Emoji('🫘', 'Beans', "U+1F9C8"),
    Emoji('🌰', 'Chestnut', "U+1F330"),
    Emoji('🍞', 'Bread', "U+1F35E"),
    Emoji('🥐', 'Croissant', "U+1F950"),
    Emoji('🥖', 'Baguette Bread', "U+1F956"),
    Emoji('🥨', 'Pretzel', "U+1F968"),
    Emoji('🥯', 'Bagel', "U+1F96F"),
    Emoji('🥞', 'Pancakes', "U+1F95E"),
    Emoji('🧀', 'Cheese Wedge', "U+1F9C0"),
    Emoji('🍖', 'Meat on Bone', "U+1F356"),
    Emoji('🍗', 'Poultry Leg', "U+1F357"),
    Emoji('🥩', 'Cut of Meat', "U+1F969"),
    Emoji('🥓', 'Bacon', "U+1F953"),
    Emoji('🍔', 'Hamburger', "U+1F354"),
    Emoji('🍟', 'French Fries', "U+1F35F"),
    Emoji('🍕', 'Pizza', "U+1F355"),
    Emoji('🌭', 'Hot Dog', "U+1F32D"),
    Emoji('🥪', 'Sandwich', "U+1F96A"),
    Emoji('🌮', 'Taco', "U+1F32E"),
    Emoji('🌯', 'Burrito', "U+1F32F"),
    Emoji('🥙', 'Stuffed Flatbread', "U+1F95A"),
    Emoji('🍳', 'Cooking', "U+1F373"),
    Emoji('🥘', 'Shallow Pan of Food', "U+1F958"),
    Emoji('🍲', 'Pot of Food', "U+1F372"),
    Emoji('🥣', 'Bowl With Spoon', "U+1F95B"),
    Emoji('🥗', 'Green Salad', "U+1F957"),
    Emoji('🍿', 'Popcorn', "U+1F37F"),
    Emoji('🧂', 'Salt', "U+1F9C2"),
    Emoji('🥫', 'Canned Food', "U+1F96B"),
    Emoji('🫙', 'Jar', "U+1F96A"),
    Emoji('🍱', 'Bento Box', "U+1F371"),
    Emoji('🍘', 'Rice Cracker', "U+1F358"),
    Emoji('🍙', 'Rice Ball', "U+1F359"),
    Emoji('🍚', 'Cooked Rice', "U+1F35A"),
    Emoji('🍛', 'Curry Rice', "U+1F35B"),
    Emoji('🍜', 'Steaming Bowl', "U+1F35C"),
    Emoji('🍝', 'Spaghetti', "U+1F35D"),
    Emoji('🍠', 'Roasted Sweet Potato', "U+1F360"),
    Emoji('🍢', 'Oden', "U+1F362"),
    Emoji('🍣', 'Sushi', "U+1F363"),
    Emoji('🍤', 'Fried Shrimp', "U+1F364"),
    Emoji('🍥', 'Fish Cake With Swirl', "U+1F365"),
    Emoji('🥮', 'Moon Cake', "U+1F96E"),
    Emoji('🍡', 'Dango', "U+1F361"),
    Emoji('🥟', 'Dumpling', "U+1F95F"),
    Emoji('🥠', 'Fortune Cookie', "U+1F960"),
    Emoji('🥡', 'Takeout Box', "U+1F961"),
    Emoji('🍦', 'Soft Ice Cream', "U+1F366"),
    Emoji('🍧', 'Shaved Ice', "U+1F367"),
    Emoji('🍨', 'Ice Cream', "U+1F368"),
    Emoji('🍩', 'Doughnut', "U+1F369"),
    Emoji('🍪', 'Cookie', "U+1F36A"),
    Emoji('🎂', 'Birthday Cake', "U+1F382"),
    Emoji('🍰', 'Shortcake', "U+1F370"),
    Emoji('🧁', 'Cupcake', "U+1F9C1"),
    Emoji('🥧', 'Pie', "U+1F967"),
    Emoji('🍫', 'Chocolate Bar', "U+1F36B"),
    Emoji('🍬', 'Candy', "U+1F36C"),
    Emoji('🍭', 'Lollipop', "U+1F36D"),
    Emoji('🍮', 'Custard', "U+1F36E"),
    Emoji('🍯', 'Honey Pot', "U+1F36F"),
    Emoji('🍼', 'Baby Bottle', "U+1F9C2"),
    Emoji('🥛', 'Glass of Milk', "U+1F95B"),
    Emoji('🫗', 'Pouring Liquid', "U+1F9CB"),
    Emoji('☕', 'Hot Beverage', "U+2615"),
    Emoji('🍵', 'Teacup Without Handle', "U+1F375"),
    Emoji('🧉', 'Mate Drink', "U+1F9C8"),
    Emoji('🍶', 'Sake', "U+1F376"),
    Emoji('🍾', 'Bottle With Popping Cork', "U+1F37E"),
    Emoji('🍷', 'Wine Glass', "U+1F377"),
    Emoji('🍸', 'Cocktail Glass', "U+1F378"),
    Emoji('🍹', 'Tropical Drink', "U+1F379"),
    Emoji('🍺', 'Beer Mug', "U+1F37A"),
    Emoji('🍻', 'Clinking Beer Mugs', "U+1F37B"),
    Emoji('🥂', 'Clinking Glasses', "U+1F942"),
    Emoji('🥃', 'Tumbler Glass', "U+1F943"),
    Emoji('🥤', 'Cup With Straw', "U+1F964"),
    Emoji('🥢', 'Chopsticks', "U+1F962"),
    Emoji('🍽️', 'Fork and Knife With Plate', "U+1F37D"),
    Emoji('🍴', 'Fork and Knife', "U+1F374"),
    Emoji('🥄', 'Spoon', "U+1F944")
  ]),

// ======================================================= Category.TRAVEL
  CategoryEmoji(Category.TRAVEL, [
    Emoji('🗾', 'Map of Japan', "U+1F5FE"),
    Emoji('🏔️', 'Snow-Capped Mountain', "U+1F3D4"),
    Emoji('⛰️', 'Mountain', "U+26F0"),
    Emoji('🌋', 'Volcano', "U+1F30B"),
    Emoji('🗻', 'Mount Fuji', "U+1F5FB"),
    Emoji('🏕️', 'Camping', "U+1F3CB"),
    Emoji('🏖️', 'Beach With Umbrella', "U+1F3D6"),
    Emoji('🏜️', 'Desert', "U+1F3DC"),
    Emoji('🏝️', 'Desert Island', "U+1F3DD"),
    Emoji('🏞️', 'National Park', "U+1F3DE"),
    Emoji('🏟️', 'Stadium', "U+1F3C stadium"),
    Emoji('🏛️', 'Classical Building', "U+1F3DB"),
    Emoji('🏗️', 'Building Construction', "U+1F3D7"),
    Emoji('🏘️', 'Houses', "U+1F3D8"),
    Emoji('🏚️', 'Derelict House', "U+1F3DA"),
    Emoji('🏠', 'House', "U+1F3E0"),
    Emoji('🏡', 'House With Garden', "U+1F3E1"),
    Emoji('🏢', 'Office Building', "U+1F3E2"),
    Emoji('🏣', 'Japanese Post Office', "U+1F3E3"),
    Emoji('🏤', 'Post Office', "U+1F3E4"),
    Emoji('🏥', 'Hospital', "U+1F3E5"),
    Emoji('🏦', 'Bank', "U+1F3E6"),
    Emoji('🏨', 'Hotel', "U+1F3E8"),
    Emoji('🏩', 'Love Hotel', "U+1F3E9"),
    Emoji('🏪', 'Convenience Store', "U+1F3EA"),
    Emoji('🏫', 'School', "U+1F3EB"),
    Emoji('🏬', 'Department Store', "U+1F3EC"),
    Emoji('🏭', 'Factory', "U+1F3ED"),
    Emoji('🏯', 'Japanese Castle', "U+1F3EF"),
    Emoji('🏰', 'Castle', "U+1F3F0"),
    Emoji('💒', 'Wedding', "U+1F492"),
    Emoji('🗼', 'Tokyo Tower', "U+1F5FC"),
    Emoji('🗽', 'Statue of Liberty', "U+1F5FD"),
    Emoji('⛪', 'Church', "U+26EA"),
    Emoji('🕌', 'Mosque', "U+1F54C"),
    Emoji('🕍', 'Synagogue', "U+1F54D"),
    Emoji('⛩️', 'Shinto Shrine', "U+26E9"),
    Emoji('🕋', 'Kaaba', "U+1F54B"),
    Emoji('⛲', 'Fountain', "U+26F2"),
    Emoji('⛺', 'Tent', "U+26FA"),
    Emoji('🌁', 'Foggy', "U+1F301"),
    Emoji('🌃', 'Night With Stars', "U+1F303"),
    Emoji('🏙️', 'Cityscape', "U+1F3D9"),
    Emoji('🌄', 'Sunrise Over Mountains', "U+1F304"),
    Emoji('🌅', 'Sunrise', "U+1F305"),
    Emoji('🌆', 'Cityscape at Dusk', "U+1F306"),
    Emoji('🌇', 'Sunset', "U+1F307"),
    Emoji('🌉', 'Bridge at Night', "U+1F308"),
    Emoji('🎠', 'Carousel Horse', "U+1F3A0"),
    Emoji('🎡', 'Ferris Wheel', "U+1F3A1"),
    Emoji('🎢', 'Roller Coaster', "U+1F3A2"),
    Emoji('🚂', 'Locomotive', "U+1F682"),
    Emoji('🚃', 'Railway Car', "U+1F683"),
    Emoji('🚄', 'High-Speed Train', "U+1F684"),
    Emoji('🚅', 'Bullet Train', "U+1F685"),
    Emoji('🚆', 'Train', "U+1F686"),
    Emoji('🚇', 'Metro', "U+1F687"),
    Emoji('🚈', 'Light Rail', "U+1F688"),
    Emoji('🚉', 'Station', "U+1F689"),
    Emoji('🚊', 'Tram', "U+1F68A"),
    Emoji('🚝', 'Monorail', "U+1F68D"),
    Emoji('🚞', 'Mountain Railway', "U+1F69E"),
    Emoji('🚋', 'Tram Car', "U+1F68B"),
    Emoji('🚌', 'Bus', "U+1F68C"),
    Emoji('🚍', 'Oncoming Bus', "U+1F68D"),
    Emoji('🚎', 'Trolleybus', "U+1F68E"),
    Emoji('🚐', 'Minibus', "U+1F690"),
    Emoji('🚑', 'Ambulance', "U+1F691"),
    Emoji('🚒', 'Fire Engine', "U+1F692"),
    Emoji('🚓', 'Police Car', "U+1F693"),
    Emoji('🚔', 'Oncoming Police Car', "U+1F694"),
    Emoji('🚕', 'Taxi', "U+1F695"),
    Emoji('🚖', 'Oncoming Taxi', "U+1F696"),
    Emoji('🚗', 'Automobile', "U+1F697"),
    Emoji('🚘', 'Oncoming Automobile', "U+1F698"),
    Emoji('🚚', 'Delivery Truck', "U+1F69A"),
    Emoji('🚛', 'Articulated Lorry', "U+1F69B"),
    Emoji('🚜', 'Tractor', "U+1F69C"),
    Emoji('🏎️', 'Racing Car', "U+1F3CE"),
    Emoji('🏍️', 'Motorcycle', "U+1F3CD"),
    Emoji('🛵', 'Motor Scooter', "U+1F6F5"),
    Emoji('🚲', 'Bicycle', "U+1F6B2"),
    Emoji('🛴', 'Kick Scooter', "U+1F6F4"),
    Emoji('🚏', 'Bus Stop', "U+1F68F"),
    Emoji('🛤️', 'Railway Track', "U+1F6E4"),
    Emoji('⛽', 'Fuel Pump', "U+26FD"),
    Emoji('🛞', 'Wheel', "U+1F6DE"),
    Emoji('🚨', 'Police Car Light', "U+1F6A8"),
    Emoji('🚥', 'Horizontal Traffic Light', "U+1F6A6"),
    Emoji('🚦', 'Vertical Traffic Light', "U+1F6A7"),
    Emoji('🚧', 'Construction', "U+1F6A7"),
    Emoji('⚓', 'Anchor', "U+2693"),
    Emoji('⛵', 'Sailboat', "U+26F5"),
    Emoji('🚤', 'Speedboat', "U+1F6A4"),
    Emoji('🛳️', 'Passenger Ship', "U+1F6A2"),
    Emoji('⛴️', 'Ferry', "U+26F4"),
    Emoji('🛥️', 'Motor Boat', "U+1F6E5"),
    Emoji('🚢', 'Ship', "U+1F6A2"),
    Emoji('🛟', 'Ring Buoy', "U+1F6E7"),
    Emoji('✈️', 'Airplane', "U+2708"),
    Emoji('🛩️', 'Small Airplane', "U+1F6E9"),
    Emoji('🛫', 'Airplane Departure', "U+1F6EB"),
    Emoji('🛬', 'Airplane Arrival', "U+1F6EC"),
    Emoji('💺', 'Seat', "U+1F4BA"),
    Emoji('🚁', 'Helicopter', "U+1F681"),
    Emoji('🚟', 'Suspension Railway', "U+1F69F"),
    Emoji('🚠', 'Mountain Cableway', "U+1F6A0"),
    Emoji('🚡', 'Aerial Tramway', "U+1F6A1"),
    Emoji('🛰️', 'Satellite', "U+1F6F0"),
    Emoji('🚀', 'Rocket', "U+1F680"),
    Emoji('🛸', 'Flying Saucer', "U+1F6F8"),
    Emoji('🌠', 'Shooting Star', "U+1F320"),
    Emoji('🌌', 'Milky Way', "U+1F304"),
    Emoji('⛱️', 'Umbrella on Ground', "U+26F1"),
    Emoji('🎆', 'Fireworks', "U+1F386"),
    Emoji('🎇', 'Sparkler', "U+1F387"),
    Emoji('🎑', 'Moon Viewing Ceremony', "U+1F38D"),
    Emoji('🗿', 'Moai', "U+1F5FF"),
    Emoji('🛂', 'Passport Control', "U+1F6C2"),
    Emoji('🛃', 'Customs', "U+1F6C3"),
    Emoji('🛄', 'Baggage Claim', "U+1F6C4"),
    Emoji('🛅', 'Left Luggage', "U+1F6C5")
  ]),

// ======================================================= Category.ACTIVITIES
  CategoryEmoji(Category.ACTIVITIES, [
    Emoji('🧗‍♂️', 'Man Climbing', "U+1F9D7 U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🧗‍♀️', 'Woman Climbing', "U+1F9D7 U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🏇', 'Horse Racing', "U+1F3C7", hasSkinTone: true),
    Emoji('⛷️', 'Skier', "U+26F7"),
    Emoji('🏂', 'Snowboarder', "U+1F3C2"),
    Emoji('🏌️‍♂️', 'Man Golfing', "U+1F3CC U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🏌️‍♀️', 'Woman Golfing', "U+1F3CC U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🏄‍♂️', 'Man Surfing', "U+1F3C4 U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🏄‍♀️', 'Woman Surfing', "U+1F3C4 U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🚣‍♂️', 'Man Rowing Boat', "U+1F6A3 U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🚣‍♀️', 'Woman Rowing Boat', "U+1F6A3 U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🏊‍♂️', 'Man Swimming', "U+1F3CA U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🏊‍♀️', 'Woman Swimming', "U+1F3CA U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('⛹️‍♂️', 'Man Bouncing Ball', "U+26F9 U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('⛹️‍♀️', 'Woman Bouncing Ball', "U+26F9 U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🏋️‍♂️', 'Man Lifting Weights', "U+1F3CB U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🏋️‍♀️', 'Woman Lifting Weights', "U+1F3CB U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🚴‍♂️', 'Man Biking', "U+1F6B4 U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🚴‍♀️', 'Woman Biking', "U+1F6B4 U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🚵‍♂️', 'Man Mountain Biking', "U+1F6B5 U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🚵‍♀️', 'Woman Mountain Biking', "U+1F6B5 U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🤸‍♂️', 'Man Cartwheeling', "U+1F938 U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🤸‍♀️', 'Woman Cartwheeling', "U+1F938 U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🤼‍♂️', 'Men Wrestling', "U+1F93C U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🤼‍♀️', 'Women Wrestling', "U+1F93C U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🤽‍♂️', 'Man Playing Water Polo', "U+1F93D U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🤽‍♀️', 'Woman Playing Water Polo', "U+1F93D U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🤾‍♂️', 'Man Playing Handball', "U+1F93E U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🤾‍♀️', 'Woman Playing Handball', "U+1F93E U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🤹‍♂️', 'Man Juggling', "U+1F939 U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🤹‍♀️', 'Woman Juggling', "U+1F939 U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🧘‍♂️', 'Man in Lotus Position', "U+1F9D8 U+200D U+2642 U+FE0F",
        hasSkinTone: true),
    Emoji('🧘‍♀️', 'Woman in Lotus Position', "U+1F9D8 U+200D U+2640 U+FE0F",
        hasSkinTone: true),
    Emoji('🎪', 'Circus Tent', "U+1F3AA"),
    Emoji('🛹', 'Skateboard', "U+1F6F9"),
    Emoji('🎗️', 'Reminder Ribbon', "U+1F397"),
    Emoji('🎟️', 'Admission Tickets', "U+1F39F"),
    Emoji('🎫', 'Ticket', "U+1F3AB"),
    Emoji('🎖️', 'Military Medal', "U+1F396"),
    Emoji('🏆', 'Trophy', "U+1F3C6"),
    Emoji('🏅', 'Sports Medal', "U+1F3C5"),
    Emoji('🥇', '1st Place Medal', "U+1F947"),
    Emoji('🥈', '2nd Place Medal', "U+1F948"),
    Emoji('🥉', '3rd Place Medal', "U+1F949"),
    Emoji('⚽', 'Soccer Ball', "U+26BD"),
    Emoji('⚾', 'Baseball', "U+26BE"),
    Emoji('🥎', 'Softball', "U+1F94E"),
    Emoji('🏀', 'Basketball', "U+1F3C0"),
    Emoji('🏐', 'Volleyball', "U+1F3D0"),
    Emoji('🏈', 'American Football', "U+1F3C8"),
    Emoji('🏉', 'Rugby Football', "U+1F3C9"),
    Emoji('🎾', 'Tennis', "U+1F3BE"),
    Emoji('🥏', 'Flying Disc', "U+1F94F"),
    Emoji('🎳', 'Bowling', "U+1F3B3"),
    Emoji('🏏', 'Cricket Game', "U+1F3CF"),
    Emoji('🏑', 'Field Hockey', "U+1F3D1"),
    Emoji('🏒', 'Ice Hockey', "U+1F3C8"),
    Emoji('🥍', 'Lacrosse', "U+1F94D"),
    Emoji('🏓', 'Ping Pong', "U+1F3D3"),
    Emoji('🏸', 'Badminton', "U+1F3F8"),
    Emoji('🪃', 'Boomerang', "U+1F83F"),
    Emoji('🥅', 'Goal Net', "U+1F945"),
    Emoji('⛳', 'Flag in Hole', "U+26F3"),
    Emoji('🪁', 'Kite', "U+1FA81"),
    Emoji('🛝', 'Playground Slide', "U+1F6E9"),
    Emoji('🏹', 'Bow and Arrow', "U+1F3F9"),
    Emoji('🎣', 'Fishing Pole', "U+1F3A3"),
    Emoji('🤿', 'Diving Mask', "U+1F93F"),
    Emoji('🥊', 'Boxing Glove', "U+1F94A"),
    Emoji('🥋', 'Martial Arts Uniform', "U+1F94B"),
    Emoji('🎽', 'Running Shirt', "U+1F3BD"),
    Emoji('🛼', 'Roller Skate', "U+1F6FC"),
    Emoji('🛷', 'Sled', "U+1F6F7"),
    Emoji('⛸️', 'Ice Skate', "U+26F8"),
    Emoji('🥌', 'Curling Stone', "U+1F94C"),
    Emoji('🎿', 'Skis', "U+1F3BF"),
    Emoji('🎯', 'Direct Hit', "U+1F3AF"),
    Emoji('🎱', 'Pool 8 Ball', "U+1F3B1"),
    Emoji('🎮', 'Video Game', "U+1F3AE"),
    Emoji('🎰', 'Slot Machine', "U+1F3B0"),
    Emoji('🎲', 'Game Die', "U+1F3B2"),
    Emoji('🧩', 'Jigsaw', "U+1F9E9"),
    Emoji('♟️', 'Chess Pawn', "U+265F"),
    Emoji('🎭', 'Performing Arts', "U+1F3AD"),
    Emoji('🎨', 'Artist Palette', "U+1F3A8"),
    Emoji('🧵', 'Thread', "U+1F9F5"),
    Emoji('🧶', 'Yarn', "U+1F9F6"),
    Emoji('🎼', 'Musical Score', "U+1F3BC"),
    Emoji('🎤', 'Microphone', "U+1F3A4"),
    Emoji('🎧', 'Headphone', "U+1F3A7"),
    Emoji('🎷', 'Saxophone', "U+1F3B7"),
    Emoji('🎸', 'Guitar', "U+1F3B8"),
    Emoji('🎹', 'Musical Keyboard', "U+1F3B9"),
    Emoji('🎺', 'Trumpet', "U+1F3BA"),
    Emoji('🎻', 'Violin', "U+1F3BB"),
    Emoji('🥁', 'Drum', "U+1F941"),
    Emoji('🎬', 'Clapper Board', "U+1F3AC")
  ]),

// ======================================================= Category.OBJECTS
  CategoryEmoji(Category.OBJECTS, [
    Emoji('💌', 'Love Letter', "U+1F48C"),
    Emoji('🕳️', 'Hole', "U+1F573"),
    Emoji('💣', 'Bomb', "U+1F4A3"),
    Emoji('🛀', 'Person Taking Bath', "U+1F6C0"),
    Emoji('🛌', 'Person in Bed', "U+1F6CC"),
    Emoji('🏺', 'Amphora', "U+1F3FA"),
    Emoji('🗺️', 'World Map', "U+1F5FA"),
    Emoji('🧭', 'Compass', "U+1F9ED"),
    Emoji('🧱', 'Brick', "U+1F9F1"),
    Emoji('💈', 'Barber Pole', "U+1F488"),
    Emoji('🛢️', 'Oil Drum', "U+1F6E2"),
    Emoji('🛎️', 'Bellhop Bell', "U+1F6CE"),
    Emoji('🧳', 'Luggage', "U+1F9F3"),
    Emoji('⌛', 'Hourglass Done', "U+231B"),
    Emoji('⏳', 'Hourglass Not Done', "U+23F3"),
    Emoji('⌚', 'Watch', "U+231A"),
    Emoji('⏰', 'Alarm Clock', "U+23F0"),
    Emoji('⏱️', 'Stopwatch', "U+23F1"),
    Emoji('⏲️', 'Timer Clock', "U+23F2"),
    Emoji('🕰️', 'Mantelpiece Clock', "U+1F570"),
    Emoji('🌡️', 'Thermometer', "U+1F321"),
    Emoji('⛱️', 'Umbrella on Ground', "U+26F1"),
    Emoji('🧨', 'Firecracker', "U+1F9E8"),
    Emoji('🎈', 'Balloon', "U+1F388"),
    Emoji('🎉', 'Party Popper', "U+1F389"),
    Emoji('🎊', 'Confetti Ball', "U+1F38A"),
    Emoji('🎎', 'Japanese Dolls', "U+1F38E"),
    Emoji('🎏', 'Carp Streamer', "U+1F38F"),
    Emoji('🎐', 'Wind Chime', "U+1F390"),
    Emoji('🪩', 'Mirror Ball', "U+1FA9A"),
    Emoji('🧧', 'Red Envelope', "U+1F9E7"),
    Emoji('🎀', 'Ribbon', "U+1F380"),
    Emoji('🎁', 'Wrapped Gift', "U+1F381"),
    Emoji('🔮', 'Crystal Ball', "U+1F52E"),
    Emoji('🧿', 'Nazar Amulet', "U+1F9FF"),
    Emoji('🪬', 'Hamsa', "U+1FA9C"),
    Emoji('🕹️', 'Joystick', "U+1F579"),
    Emoji('🧸', 'Teddy Bear', "U+1F9F8"),
    Emoji('🖼️', 'Framed Picture', "U+1F5BC"),
    Emoji('🧵', 'Thread', "U+1F9F5"),
    Emoji('🧶', 'Yarn', "U+1F9F6"),
    Emoji('🛍️', 'Shopping Bags', "U+1F3C7"),
    Emoji('📿', 'Prayer Beads', "U+1F4FF"),
    Emoji('💎', 'Gem Stone', "U+1F48E"),
    Emoji('📯', 'Postal Horn', "U+1F4EF"),
    Emoji('🎙️', 'Studio Microphone', "U+1F399"),
    Emoji('🎚️', 'Level Slider', "U+1F39A"),
    Emoji('🎛️', 'Control Knobs', "U+1F39B"),
    Emoji('📻', 'Radio', "U+1F4FB"),
    Emoji('📱', 'Mobile Phone', "U+1F4F1"),
    Emoji('📲', 'Mobile Phone With Arrow', "U+1F4F2"),
    Emoji('☎️', 'Telephone', "U+260E"),
    Emoji('📞', 'Telephone Receiver', "U+1F4DE"),
    Emoji('📟', 'Pager', "U+1F4DF"),
    Emoji('📠', 'Fax Machine', "U+1F4E0"),
    Emoji('🔋', 'Battery', "U+1F50B"),
    Emoji('🪫', 'Low Battery', "U+1FAAB"),
    Emoji('🔌', 'Electric Plug', "U+1F50C"),
    Emoji('💻', 'Laptop Computer', "U+1F4BB"),
    Emoji('🖥️', 'Desktop Computer', "U+1F5A5"),
    Emoji('🖨️', 'Printer', "U+1F5A8"),
    Emoji('⌨️', 'Keyboard', "U+2328"),
    Emoji('🖱️', 'Computer Mouse', "U+1F5B1"),
    Emoji('🖲️', 'Trackball', "U+1F5B2"),
    Emoji('💽', 'Computer Disk', "U+1F4BD"),
    Emoji('💾', 'Floppy Disk', "U+1F4BE"),
    Emoji('💿', 'Optical Disk', "U+1F4BF"),
    Emoji('📀', 'DVD', "U+1F4C0"),
    Emoji('🧮', 'Abacus', "U+1F9EE"),
    Emoji('🎥', 'Movie Camera', "U+1F3A5"),
    Emoji('🎞️', 'Film Frames', "U+1F39E"),
    Emoji('📽️', 'Film Projector', "U+1F4FD"),
    Emoji('📺', 'Television', "U+1F4FA"),
    Emoji('📷', 'Camera', "U+1F4F7"),
    Emoji('📸', 'Camera With Flash', "U+1F4F8"),
    Emoji('📹', 'Video Camera', "U+1F4F9"),
    Emoji('📼', 'Videocassette', "U+1F4FC"),
    Emoji('🔍', 'Magnifying Glass Tilted Left', "U+1F50D"),
    Emoji('🔎', 'Magnifying Glass Tilted Right', "U+1F50E"),
    Emoji('🕯️', 'Candle', "U+1F56F"),
    Emoji('💡', 'Light Bulb', "U+1F4A1"),
    Emoji('🔦', 'Flashlight', "U+1F526"),
    Emoji('🏮', 'Red Paper Lantern', "U+1F3EE"),
    Emoji('📔', 'Notebook With Decorative Cover', "U+1F4D4"),
    Emoji('📕', 'Closed Book', "U+1F4D5"),
    Emoji('📖', 'Open Book', "U+1F4D6"),
    Emoji('📗', 'Green Book', "U+1F4D7"),
    Emoji('📘', 'Blue Book', "U+1F4D8"),
    Emoji('📙', 'Orange Book', "U+1F4D9"),
    Emoji('📚', 'Books', "U+1F4DA"),
    Emoji('📓', 'Notebook', "U+1F4D3"),
    Emoji('📃', 'Page With Curl', "U+1F40C"),
    Emoji('📜', 'Scroll', "U+1F4DC"),
    Emoji('📄', 'Page Facing Up', "U+1F4C4"),
    Emoji('📰', 'Newspaper', "U+1F4F0"),
    Emoji('🗞️', 'Rolled-Up Newspaper', "U+1F5DE"),
    Emoji('📑', 'Bookmark Tabs', "U+1F4D1"),
    Emoji('🔖', 'Bookmark', "U+1F516"),
    Emoji('🏷️', 'Label', "U+1F3F7"),
    Emoji('💰', 'Money Bag', "U+1F4B0"),
    Emoji('💴', 'Yen Banknote', "U+1F4B4"),
    Emoji('💵', 'Dollar Banknote', "U+1F4B5"),
    Emoji('💶', 'Euro Banknote', "U+1F4B6"),
    Emoji('💷', 'Pound Banknote', "U+1F4B7"),
    Emoji('💸', 'Money With Wings', "U+1F4B8"),
    Emoji('💳', 'Credit Card', "U+1F4B3"),
    Emoji('🪪', 'Identification Card', "U+1FAE9"),
    Emoji('🧾', 'Receipt', "U+1F9FE"),
    Emoji('✉️', 'Envelope', "U+2709"),
    Emoji('📧', 'E-Mail', "U+1F4E7"),
    Emoji('📨', 'Incoming Envelope', "U+1F4E8"),
    Emoji('📩', 'Envelope With Arrow', "U+1F4E9"),
    Emoji('📤', 'Outbox Tray', "U+1F4E4"),
    Emoji('📥', 'Inbox Tray', "U+1F4E5"),
    Emoji('📦', 'Package', "U+1F4E6"),
    Emoji('📫', 'Closed Mailbox With Raised Flag', "U+1F4EB"),
    Emoji('📪', 'Closed Mailbox With Lowered Flag', "U+1F4EA"),
    Emoji('📬', 'Open Mailbox With Raised Flag', "U+1F4EC"),
    Emoji('📭', 'Open Mailbox With Lowered Flag', "U+1F4ED"),
    Emoji('📮', 'Postbox', "U+1F4EE"),
    Emoji('🗳️', 'Ballot Box With Ballot', "U+1F5F3"),
    Emoji('✏️', 'Pencil', "U+270F"),
    Emoji('✒️', 'Black Nib', "U+2712"),
    Emoji('🖋️', 'Fountain Pen', "U+1F58B"),
    Emoji('🖊️', 'Pen', "U+1F58A"),
    Emoji('🖌️', 'Paintbrush', "U+1F58C"),
    Emoji('🖍️', 'Crayon', "U+1F58D"),
    Emoji('📝', 'Memo', "U+1F5E8"),
    Emoji('📁', 'File Folder', "U+1F4C1"),
    Emoji('📂', 'Open File Folder', "U+1F4C2"),
    Emoji('🗂️', 'Card Index Dividers', "U+1F5C2"),
    Emoji('📅', 'Calendar', "U+1F4C5"),
    Emoji('📆', 'Tear-Off Calendar', "U+1F4C6"),
    Emoji('🗒️', 'Spiral Notepad', "U+1F5D2"),
    Emoji('🗓️', 'Spiral Calendar', "U+1F5D3"),
    Emoji('📇', 'Card Index', "U+1F4C7"),
    Emoji('📈', 'Chart Increasing', "U+1F4C8"),
    Emoji('📉', 'Chart Decreasing', "U+1F4C9"),
    Emoji('📊', 'Bar Chart', "U+1F4CA"),
    Emoji('📋', 'Clipboard', "U+1F4CB"),
    Emoji('📌', 'Pushpin', "U+1F4CC"),
    Emoji('📍', 'Round Pushpin', "U+1F4CD"),
    Emoji('📎', 'Paperclip', "U+1F4CE"),
    Emoji('🖇️', 'Linked Paperclips', "U+1F587"),
    Emoji('📏', 'Straight Ruler', "U+1F4CF"),
    Emoji('📐', 'Triangular Ruler', "U+1F4D0"),
    Emoji('✂️', 'Scissors', "U+2702"),
    Emoji('🗃️', 'Card File Box', "U+1F5C3"),
    Emoji('🗄️', 'File Cabinet', "U+1F5C4"),
    Emoji('🗑️', 'Wastebasket', "U+1F5D1"),
    Emoji('🔒', 'Locked', "U+1F512"),
    Emoji('🔓', 'Unlocked', "U+1F513"),
    Emoji('🔏', 'Locked With Pen', "U+1F50F"),
    Emoji('🔐', 'Locked With Key', "U+1F510"),
    Emoji('🔑', 'Key', "U+1F511"),
    Emoji('🗝️', 'Old Key', "U+1F5E1"),
    Emoji('🔨', 'Hammer', "U+1F528"),
    Emoji('⛏️', 'Pick', "U+26CF"),
    Emoji('⚒️', 'Hammer and Pick', "U+2692"),
    Emoji('🛠️', 'Hammer and Wrench', "U+1F6E0"),
    Emoji('🔪', 'Kitchen Knife', "U+1F52A"),
    Emoji('🗡️', 'Dagger', "U+1F5E1"),
    Emoji('⚔️', 'Crossed Swords', "U+2694"),
    Emoji('🔫', 'Pistol', "U+1F52B"),
    Emoji('🛡️', 'Shield', "U+1F6E1"),
    Emoji('🔧', 'Wrench', "U+1F527"),
    Emoji('🔩', 'Nut and Bolt', "U+1F529"),
    Emoji('⚙️', 'Gear', "U+2699"),
    Emoji('🗜️', 'Clamp', "U+1F5DC"),
    Emoji('⚖️', 'Balance Scale', "U+2696"),
    Emoji('🔗', 'Link', "U+1F517"),
    Emoji('⛓️', 'Chains', "U+26D3"),
    Emoji('🧰', 'Toolbox', "U+1F9F0"),
    Emoji('🧲', 'Magnet', "U+1F9F2"),
    Emoji('⚗️', 'Alembic', "U+2697"),
    Emoji('🧪', 'Test Tube', "U+1F9EA"),
    Emoji('🧫', 'Petri Dish', "U+1F9EB"),
    Emoji('🧬', 'DNA', "U+1F9EC"),
    Emoji('🔬', 'Microscope', "U+1F52C"),
    Emoji('🩻', 'X-Ray', "U+1FA7B"),
    Emoji('🔭', 'Telescope', "U+1F52D"),
    Emoji('📡', 'Satellite Antenna', "U+1F4E1"),
    Emoji('💉', 'Syringe', "U+1F489"),
    Emoji('💊', 'Pill', "U+1F48A"),
    Emoji('🚪', 'Door', "U+1F6AA"),
    Emoji('🛏️', 'Bed', "U+1F6CF"),
    Emoji('🛋️', 'Couch and Lamp', "U+1F6CB"),
    Emoji('🚽', 'Toilet', "U+1F6BD"),
    Emoji('🚿', 'Shower', "U+1F6BF"),
    Emoji('🛁', 'Bathtub', "U+1F6C1"),
    Emoji('🧴', 'Lotion Bottle', "U+1F9F4"),
    Emoji('🧷', 'Safety Pin', "U+1F9F7"),
    Emoji('🧹', 'Broom', "U+1F9F9"),
    Emoji('🧺', 'Basket', "U+1F9FA"),
    Emoji('🧻', 'Roll of Paper', "U+1F9FB"),
    Emoji('🧼', 'Soap', "U+1F9FC"),
    Emoji('🧽', 'Sponge', "U+1F9FD"),
    Emoji('🧯', 'Fire Extinguisher', "U+1F9EF"),
    Emoji('🚬', 'Cigarette', "U+1F6AC"),
    Emoji('⚰️', 'Coffin', "U+26B0"),
    Emoji('⚱️', 'Funeral Urn', "U+26B1"),
    Emoji('🚰', 'Potable Water', "U+1F6B0")
  ]),

// ======================================================= Category.SYMBOLS
  CategoryEmoji(Category.SYMBOLS, [
    Emoji('💘', 'Heart With Arrow', "U+1F498"),
    Emoji('💝', 'Heart With Ribbon', "U+1F49D"),
    Emoji('💖', 'Sparkling Heart', "U+1F496"),
    Emoji('💗', 'Growing Heart', "U+1F497"),
    Emoji('💓', 'Beating Heart', "U+1F493"),
    Emoji('💞', 'Revolving Hearts', "U+1F49C"),
    Emoji('💕', 'Two Hearts', "U+1F495"),
    Emoji('💟', 'Heart Decoration', "U+1F49F"),
    Emoji('❣️', 'Heavy Heart Exclamation', "U+2763"),
    Emoji('💔', 'Broken Heart', "U+1F494"),
    Emoji('❤️', 'Red Heart', "U+2764"),
    Emoji('🧡', 'Orange Heart', "U+1F9C7"),
    Emoji('💛', 'Yellow Heart', "U+1F49B"),
    Emoji('💚', 'Green Heart', "U+1F49A"),
    Emoji('💙', 'Blue Heart', "U+1F499"),
    Emoji('💜', 'Purple Heart', "U+1F49C"),
    Emoji('🖤', 'Black Heart', "U+1F5A4"),
    Emoji('💯', 'Hundred Points', "U+1F4AF"),
    Emoji('💢', 'Anger Symbol', "U+1F4A2"),
    Emoji('💬', 'Speech Balloon', "U+1F4AC"),
    Emoji('👁️‍🗨️', 'Eye in Speech Bubble', "U+1F441 U+FE0F U+200D U+1F5E8"),
    Emoji('🗯️', 'Right Anger Bubble', "U+1F5EF"),
    Emoji('💭', 'Thought Balloon', "U+1F4AD"),
    Emoji('💤', 'Zzz', "U+1F4A4"),
    Emoji('💮', 'White Flower', "U+1F4A6"),
    Emoji('♨️', 'Hot Springs', "U+2668"),
    Emoji('💈', 'Barber Pole', "U+1F488"),
    Emoji('🛑', 'Stop Sign', "U+1F6D1"),
    Emoji('🕛', 'Twelve O’Clock', "U+1F55B"),
    Emoji('🕧', 'Twelve-Thirty', "U+1F567"),
    Emoji('🕐', 'One O’Clock', "U+1F550"),
    Emoji('🕜', 'One-Thirty', "U+1F55C"),
    Emoji('🕑', 'Two O’Clock', "U+1F551"),
    Emoji('🕝', 'Two-Thirty', "U+1F55D"),
    Emoji('🕒', 'Three O’Clock', "U+1F552"),
    Emoji('🕞', 'Three-Thirty', "U+1F55E"),
    Emoji('🕓', 'Four O’Clock', "U+1F553"),
    Emoji('🕟', 'Four-Thirty', "U+1F55F"),
    Emoji('🕔', 'Five O’Clock', "U+1F554"),
    Emoji('🕠', 'Five-Thirty', "U+1F560"),
    Emoji('🕕', 'Six O’Clock', "U+1F555"),
    Emoji('🕡', 'Six-Thirty', "U+1F561"),
    Emoji('🕖', 'Seven O’Clock', "U+1F556"),
    Emoji('🕢', 'Seven-Thirty', "U+1F562"),
    Emoji('🕗', 'Eight O’Clock', "U+1F557"),
    Emoji('🕣', 'Eight-Thirty', "U+1F563"),
    Emoji('🕘', 'Nine O’Clock', "U+1F558"),
    Emoji('🕤', 'Nine-Thirty', "U+1F564"),
    Emoji('🕙', 'Ten O’Clock', "U+1F559"),
    Emoji('🕥', 'Ten-Thirty', "U+1F565"),
    Emoji('🕚', 'Eleven O’Clock', "U+1F55A"),
    Emoji('🕦', 'Eleven-Thirty', "U+1F566"),
    Emoji('🌀', 'Cyclone', "U+1F300"),
    Emoji('♠️', 'Spade Suit', "U+2660"),
    Emoji('♥️', 'Heart Suit', "U+2665"),
    Emoji('♦️', 'Diamond Suit', "U+2666"),
    Emoji('♣️', 'Club Suit', "U+2663"),
    Emoji('🃏', 'Joker', "U+1F0CF"),
    Emoji('🀄', 'Mahjong Red Dragon', "U+1F004"),
    Emoji('🎴', 'Flower Playing Cards', "U+1F3B4"),
    Emoji('🔇', 'Muted Speaker', "U+1F507"),
    Emoji('🔈', 'Speaker Low Volume', "U+1F508"),
    Emoji('🔉', 'Speaker Medium Volume', "U+1F509"),
    Emoji('🔊', 'Speaker High Volume', "U+1F50A"),
    Emoji('📢', 'Loudspeaker', "U+1F4E3"),
    Emoji('📣', 'Megaphone', "U+1F4E2"),
    Emoji('📯', 'Postal Horn', "U+1F4EF"),
    Emoji('🔔', 'Bell', "U+1F514"),
    Emoji('🔕', 'Bell With Slash', "U+1F515"),
    Emoji('🎵', 'Musical Note', "U+1F3B5"),
    Emoji('🎶', 'Musical Notes', "U+1F3B6"),
    Emoji('🏧', 'ATM Sign', "U+1F3E7"),
    Emoji('🚮', 'Litter in Bin Sign', "U+1F5E9"),
    Emoji('🚰', 'Potable Water', "U+1F6B0"),
    Emoji('♿', 'Wheelchair Symbol', "U+267F"),
    Emoji('🩼', 'Crutch', "U+1FA9C"),
    Emoji('🚹', 'Men’s Room', "U+1F6B9"),
    Emoji('🚺', 'Women’s Room', "U+1F6BA"),
    Emoji('🚻', 'Restroom', "U+1F6BB"),
    Emoji('🚼', 'Baby Symbol', "U+1F6BC"),
    Emoji('🚾', 'Water Closet', "U+1F6BE"),
    Emoji('⚠️', 'Warning', "U+26A0"),
    Emoji('🚸', 'Children Crossing', "U+1F6B8"),
    Emoji('⛔', 'No Entry', "U+26D6"),
    Emoji('🚫', 'Prohibited', "U+1F6AB"),
    Emoji('🚳', 'No Bicycles', "U+1F6B3"),
    Emoji('🚭', 'No Smoking', "U+1F6AD"),
    Emoji('🚯', 'No Littering', "U+1F6AF"),
    Emoji('🚱', 'Non-Potable Water', "U+1F6B1"),
    Emoji('🚷', 'No Pedestrians', "U+1F6B7"),
    Emoji('🔞', 'No One Under Eighteen', "U+1F51E"),
    Emoji('☢️', 'Radioactive', "U+2622"),
    Emoji('☣️', 'Biohazard', "U+2623"),
    Emoji('⬆️', 'Up Arrow', "U+2B06"),
    Emoji('↗️', 'Up-Right Arrow', "U+2197"),
    Emoji('➡️', 'Right Arrow', "U+27A1"),
    Emoji('↘️', 'Down-Right Arrow', "U+2198"),
    Emoji('⬇️', 'Down Arrow', "U+2B07"),
    Emoji('↙️', 'Down-Left Arrow', "U+2199"),
    Emoji('⬅️', 'Left Arrow', "U+2B05"),
    Emoji('↖️', 'Up-Left Arrow', "U+2196"),
    Emoji('↕️', 'Up-Down Arrow', "U+2195"),
    Emoji('↔️', 'Left-Right Arrow', "U+2194"),
    Emoji('↩️', 'Right Arrow Curving Left', "U+21A9"),
    Emoji('↪️', 'Left Arrow Curving Right', "U+21AA"),
    Emoji('⤴️', 'Right Arrow Curving Up', "U+2934"),
    Emoji('⤵️', 'Right Arrow Curving Down', "U+2935"),
    Emoji('🔃', 'Clockwise Vertical Arrows', "U+1F503"),
    Emoji('🔄', 'Counterclockwise Arrows Button', "U+1F504"),
    Emoji('🔙', 'Back Arrow', "U+1F519"),
    Emoji('🔚', 'End Arrow', "U+1F51A"),
    Emoji('🔛', 'On! Arrow', "U+1F51B"),
    Emoji('🔜', 'Soon Arrow', "U+1F51C"),
    Emoji('🔝', 'Top Arrow', "U+1F51D"),
    Emoji('🛐', 'Place of Worship', "U+1F6D0"),
    Emoji('⚛️', 'Atom Symbol', "U+269B"),
    Emoji('🕉️', 'Om', "U+1F549"),
    Emoji('✡️', 'Star of David', "U+2721"),
    Emoji('☸️', 'Wheel of Dharma', "U+2638"),
    Emoji('☯️', 'Yin Yang', "U+262F"),
    Emoji('✝️', 'Latin Cross', "U+271D"),
    Emoji('☦️', 'Orthodox Cross', "U+2626"),
    Emoji('☪️', 'Star and Crescent', "U+262A"),
    Emoji('☮️', 'Peace Symbol', "U+262E"),
    Emoji('🕎', 'Menorah', "U+1F54E"),
    Emoji('🔯', 'Dotted Six-Pointed Star', "U+1F52F"),
    Emoji('♈', 'Aries', "U+2648"),
    Emoji('♉', 'Taurus', "U+2649"),
    Emoji('♊', 'Gemini', "U+264A"),
    Emoji('♋', 'Cancer', "U+264B"),
    Emoji('♌', 'Leo', "U+264C"),
    Emoji('♍', 'Virgo', "U+264D"),
    Emoji('♎', 'Libra', "U+264E"),
    Emoji('♏', 'Scorpio', "U+264F"),
    Emoji('♐', 'Sagittarius', "U+2600"),
    Emoji('♑', 'Capricorn', "U+2651"),
    Emoji('♒', 'Aquarius', "U+2652"),
    Emoji('♓', 'Pisces', "U+2653"),
    Emoji('⛎', 'Ophiuchus', "U+26CE"),
    Emoji('🔀', 'Shuffle Tracks Button', "U+1F500"),
    Emoji('🔁', 'Repeat Button', "U+1F501"),
    Emoji('🔂', 'Repeat Single Button', "U+1F502"),
    Emoji('▶️', 'Play Button', "U+25B6"),
    Emoji('⏩', 'Fast-Forward Button', "U+23E9"),
    Emoji('◀️', 'Reverse Button', "U+25C0"),
    Emoji('⏪', 'Fast Reverse Button', "U+23EA"),
    Emoji('🔼', 'Upwards Button', "U+1F53C"),
    Emoji('⏫', 'Fast Up Button', "U+23EB"),
    Emoji('🔽', 'Downwards Button', "U+1F53D"),
    Emoji('⏬', 'Fast Down Button', "U+23EC"),
    Emoji('⏹️', 'Stop Button', "U+23F9"),
    Emoji('⏏️', 'Eject Button', "U+23CF"),
    Emoji('🎦', 'Cinema', "U+1F3A6"),
    Emoji('🔅', 'Dim Button', "U+1F505"),
    Emoji('🔆', 'Bright Button', "U+1F506"),
    Emoji('📶', 'Antenna Bars', "U+1F4F6"),
    Emoji('📳', 'Vibration Mode', "U+1F4F3"),
    Emoji('📴', 'Mobile Phone Off', "U+1F4F4"),
    Emoji('♾️', 'Infinity', "U+267E"),
    Emoji('♻️', 'Recycling Symbol', "U+267B"),
    Emoji('🔱', 'Trident Emblem', "U+1F531"),
    Emoji('📛', 'Name Badge', "U+1F4DB"),
    Emoji('🔰', 'Japanese Symbol for Beginner', "U+1F530"),
    Emoji('⭕', 'Heavy Large Circle', "U+2B55"),
    Emoji('✅', 'White Heavy Check Mark', "U+2705"),
    Emoji('☑️', 'Ballot Box With Check', "U+2611"),
    Emoji('✔️', 'Heavy Check Mark', "U+2714"),
    Emoji('❌', 'Cross Mark', "U+274C"),
    Emoji('❎', 'Cross Mark Button', "U+274E"),
    Emoji('➕', 'Heavy Plus Sign', "U+2795"),
    Emoji('➖', 'Heavy Minus Sign', "U+2796"),
    Emoji('➗', 'Heavy Division Sign', "U+2797"),
    Emoji('✖️', 'Heavy Multiplication X', "U+2716"),
    Emoji('🟰', 'Heavy Equals Sign', "U+1F7F0"),
    Emoji('➰', 'Curly Loop', "U+27B0"),
    Emoji('➿', 'Double Curly Loop', "U+27BF"),
    Emoji('〽️', 'Part Alternation Mark', "U+303D"),
    Emoji('✳️', 'Eight-Spoked Asterisk', "U+2733"),
    Emoji('✴️', 'Eight-Pointed Star', "U+2734"),
    Emoji('❇️', 'Sparkle', "U+2747"),
    Emoji('‼️', 'Double Exclamation Mark', "U+203C"),
    Emoji('⁉️', 'Exclamation Question Mark', "U+2049"),
    Emoji('❓', 'Question Mark', "U+2753"),
    Emoji('❔', 'White Question Mark', "U+2754"),
    Emoji('❕', 'White Exclamation Mark', "U+2755"),
    Emoji('❗', 'Exclamation Mark', "U+2757"),
    Emoji('©️', 'Copyright', "U+00A9"),
    Emoji('®️', 'Registered', "U+00AE"),
    Emoji('™️', 'Trade Mark', "U+2122"),
    Emoji('#️⃣', 'Keycap Number Sign', "U+0023 U+FE0F U+20E3"),
    Emoji('0️⃣', 'Keycap Digit Zero', "U+0030 U+FE0F U+20E3"),
    Emoji('1️⃣', 'Keycap Digit One', "U+0031 U+FE0F U+20E3"),
    Emoji('2️⃣', 'Keycap Digit Two', "U+0032 U+FE0F U+20E3"),
    Emoji('3️⃣', 'Keycap Digit Three', "U+0033 U+FE0F U+20E3"),
    Emoji('4️⃣', 'Keycap Digit Four', "U+0034 U+FE0F U+20E3"),
    Emoji('5️⃣', 'Keycap Digit Five', "U+0035 U+FE0F U+20E3"),
    Emoji('6️⃣', 'Keycap Digit Six', "U+0036 U+FE0F U+20E3"),
    Emoji('7️⃣', 'Keycap Digit Seven', "U+0037 U+FE0F U+20E3"),
    Emoji('8️⃣', 'Keycap Digit Eight', "U+0038 U+FE0F U+20E3"),
    Emoji('9️⃣', 'Keycap Digit Nine', "U+0039 U+FE0F U+20E3"),
    Emoji('🔟', 'Keycap: 10', "U+1F51F"),
    Emoji('🔠', 'Input Latin Uppercase', "U+1F520"),
    Emoji('🔡', 'Input Latin Lowercase', "U+1F521"),
    Emoji('🔢', 'Input Numbers', "U+1F522"),
    Emoji('🔣', 'Input Symbols', "U+1F523"),
    Emoji('🔤', 'Input Latin Letters', "U+1F524"),
    Emoji('🅰️', 'A Button (Blood Type)', "U+1F170"),
    Emoji('🆎', 'AB Button (Blood Type)', "U+1F471"),
    Emoji('🅱️', 'B Button (Blood Type)', "U+1F171"),
    Emoji('🆑', 'CL Button', "U+1F191"),
    Emoji('🆒', 'Cool Button', "U+1F192"),
    Emoji('🆓', 'Free Button', "U+1F193"),
    Emoji('ℹ️', 'Information', "U+2139"),
    Emoji('🆔', 'ID Button', "U+1F194"),
    Emoji('Ⓜ️', 'Circled M', "U+24C2"),
    Emoji('🆕', 'New Button', "U+1F195"),
    Emoji('🆖', 'NG Button', "U+1F196"),
    Emoji('🅾️', 'O Button (Blood Type)', "U+1F17E"),
    Emoji('🆗', 'OK Button', "U+1F197"),
    Emoji('🅿️', 'P Button', "U+1F17F"),
    Emoji('🆘', 'SOS Button', "U+1F198"),
    Emoji('🆙', 'Up! Button', "U+1F199"),
    Emoji('🆚', 'Vs Button', "U+1F19A"),
    Emoji('🈁', 'Japanese “Here” Button', "U+1F201"),
    Emoji('🈂️', 'Japanese “Service Charge” Button', "U+1F202"),
    Emoji('🈷️', 'Japanese “Monthly Amount” Button', "U+1F196"),
    Emoji('🈶', 'Japanese “Not Free of Charge” Button', "U+1F6E6"),
    Emoji('🈯', 'Japanese “Reserved” Button', "U+1F12F"),
    Emoji('🉐', 'Japanese “Bargain” Button', "U+1F250"),
    Emoji('🈹', 'Japanese “Discount” Button', "U+1F239"),
    Emoji('🈚', 'Japanese “Free of Charge” Button', "U+1F21A"),
    Emoji('🈲', 'Japanese “Prohibited” Button', "U+1F232"),
    Emoji('🉑', 'Japanese “Acceptable” Button', "U+1F251"),
    Emoji('🈸', 'Japanese “Application” Button', "U+1F238"),
    Emoji('🈴', 'Japanese “Passing Grade” Button', "U+1F234"),
    Emoji('🈳', 'Japanese “Vacancy” Button', "U+1F233"),
    Emoji('㊗️', 'Japanese “Congratulations” Button', "U+3297"),
    Emoji('㊙️', 'Japanese “Secret” Button', "U+3299"),
    Emoji('🈺', 'Japanese “Open for Business” Button', "U+1F23A"),
    Emoji('🈵', 'Japanese “No Vacancy” Button', "U+1F235"),
    Emoji('🔴', 'Red Circle', "U+1F534"),
    Emoji('🔵', 'Blue Circle', "U+1F535"),
    Emoji('⚫', 'Black Circle', "U+26AB"),
    Emoji('⚪', 'White Circle', "U+26AA"),
    Emoji('⬛', 'Black Large Square', "U+2B1B"),
    Emoji('⬜', 'White Large Square', "U+2B1C"),
    Emoji('◼️', 'Black Medium Square', "U+25FC"),
    Emoji('◻️', 'White Medium Square', "U+25FB"),
    Emoji('◾', 'Black Medium-Small Square', "U+25FE"),
    Emoji('◽', 'White Medium-Small Square', "U+25FD"),
    Emoji('▪️', 'Black Small Square', "U+25AA"),
    Emoji('▫️', 'White Small Square', "U+25AB"),
    Emoji('🔶', 'Large Orange Diamond', "U+1F536"),
    Emoji('🔷', 'Large Blue Diamond', "U+1F537"),
    Emoji('🔸', 'Small Orange Diamond', "U+1F538"),
    Emoji('🔹', 'Small Blue Diamond', "U+1F539"),
    Emoji('🔺', 'Red Triangle Pointed Up', "U+1F53A"),
    Emoji('🔻', 'Red Triangle Pointed Down', "U+1F53B"),
    Emoji('💠', 'Diamond With a Dot', "U+1F4A0"),
    Emoji('🔳', 'White Square Button', "U+1F533"),
    Emoji('🔲', 'Black Square Button', "U+1F532"),
  ]),

// ======================================================= Category.FLAGS
  CategoryEmoji(Category.FLAGS, [
    Emoji('🏁', 'Chequered Flag', "U+1F3C1"),
    Emoji('🚩', 'Triangular Flag', "U+1F6A9"),
    Emoji('🎌', 'Crossed Flags', "U+1F38C"),
    Emoji('🏴', 'Black Flag', "U+1F3F4"),
    Emoji('🏳️', 'White Flag', "U+1F3F3"),
    Emoji('🏳️‍🌈', 'Rainbow Flag', "U+1F3F3 U+FE0F U+200D U+1F308"),
    Emoji('🏴‍☠️', 'Pirate Flag', "U+1F3F4 U+200D U+2620"),
    Emoji('🇦🇨', 'Flag: Ascension Island', "U+1F1E6 U+1F1E8"),
    Emoji('🇦🇩', 'Flag: Andorra', "U+1F1E6 U+1F1E9"),
    Emoji('🇦🇪', 'Flag: United Arab Emirates', "U+1F1E6 U+1F1EA"),
    Emoji('🇦🇫', 'Flag: Afghanistan', "U+1F1E6 U+1F1EB"),
    Emoji('🇦🇬', 'Flag: Antigua & Barbuda', "U+1F1E6 U+1F1EC"),
    Emoji('🇦🇮', 'Flag: Anguilla', "U+1F1E6 U+1F1EE"),
    Emoji('🇦🇱', 'Flag: Albania', "U+1F1E6 U+1F1F1"),
    Emoji('🇦🇲', 'Flag: Armenia', "U+1F1E6 U+1F1F2"),
    Emoji('🇦🇴', 'Flag: Angola', "U+1F1E6 U+1F1F4"),
    Emoji('🇦🇶', 'Flag: Antarctica', "U+1F1E6 U+1F1F6"),
    Emoji('🇦🇷', 'Flag: Argentina', "U+1F1E6 U+1F1F7"),
    Emoji('🇦🇸', 'Flag: American Samoa', "U+1F1E6 U+1F1F8"),
    Emoji('🇦🇹', 'Flag: Austria', "U+1F1E6 U+1F1F9"),
    Emoji('🇦🇺', 'Flag: Australia', "U+1F1E6 U+1F1FA"),
    Emoji('🇦🇼', 'Flag: Aruba', "U+1F1E6 U+1F1FC"),
    Emoji('🇦🇽', 'Flag: Åland Islands', "U+1F1E6 U+1F1FD"),
    Emoji('🇦🇿', 'Flag: Azerbaijan', "U+1F1E6 U+1F1FF"),
    Emoji('🇧🇦', 'Flag: Bosnia & Herzegovina', "U+1F1E7 U+1F1E6"),
    Emoji('🇧🇧', 'Flag: Barbados', "U+1F1E7 U+1F1E7"),
    Emoji('🇧🇩', 'Flag: Bangladesh', "U+1F1E7 U+1F1E9"),
    Emoji('🇧🇪', 'Flag: Belgium', "U+1F1E7 U+1F1EA"),
    Emoji('🇧🇫', 'Flag: Burkina Faso', "U+1F1E7 U+1F1EB"),
    Emoji('🇧🇬', 'Flag: Bulgaria', "U+1F1E7 U+1F1EC"),
    Emoji('🇧🇭', 'Flag: Bahrain', "U+1F1E7 U+1F1ED"),
    Emoji('🇧🇮', 'Flag: Burundi', "U+1F1E7 U+1F1EE"),
    Emoji('🇧🇯', 'Flag: Benin', "U+1F1E7 U+1F1EF"),
    Emoji('🇧🇱', 'Flag: St. Barthélemy', "U+1F1E7 U+1F1F1"),
    Emoji('🇧🇲', 'Flag: Bermuda', "U+1F1E7 U+1F1F2"),
    Emoji('🇧🇳', 'Flag: Brunei', "U+1F1E7 U+1F1F3"),
    Emoji('🇧🇴', 'Flag: Bolivia', "U+1F1E7 U+1F1F4"),
    Emoji('🇧🇶', 'Flag: Caribbean Netherlands', "U+1F1E7 U+1F1F6"),
    Emoji('🇧🇷', 'Flag: Brazil', "U+1F1E7 U+1F1F7"),
    Emoji('🇧🇸', 'Flag: Bahamas', "U+1F1E7 U+1F1F8"),
    Emoji('🇧🇹', 'Flag: Bhutan', "U+1F1E7 U+1F1F9"),
    Emoji('🇧🇻', 'Flag: Bouvet Island', "U+1F1E7 U+1F1FB"),
    Emoji('🇧🇼', 'Flag: Botswana', "U+1F1E7 U+1F1FC"),
    Emoji('🇧🇾', 'Flag: Belarus', "U+1F1E7 U+1F1FE"),
    Emoji('🇧🇿', 'Flag: Belize', "U+1F1E7 U+1F1FF"),
    Emoji('🇨🇦', 'Flag: Canada', "U+1F1E8 U+1F1E6"),
    Emoji('🇨🇨', 'Flag: Cocos (Keeling) Islands', "U+1F1E8 U+1F1E8"),
    Emoji('🇨🇩', 'Flag: Congo - Kinshasa', "U+1F1E8 U+1F1E9"),
    Emoji('🇨🇫', 'Flag: Central African Republic', "U+1F1E8 U+1F1EB"),
    Emoji('🇨🇬', 'Flag: Congo - Brazzaville', "U+1F1E8 U+1F1EC"),
    Emoji('🇨🇭', 'Flag: Switzerland', "U+1F1E8 U+1F1ED"),
    Emoji('🇨🇮', 'Flag: Côte d’Ivoire', "U+1F1E8 U+1F1EE"),
    Emoji('🇨🇰', 'Flag: Cook Islands', "U+1F1E8 U+1F1F0"),
    Emoji('🇨🇱', 'Flag: Chile', "U+1F1E8 U+1F1F1"),
    Emoji('🇨🇲', 'Flag: Cameroon', "U+1F1E8 U+1F1F2"),
    Emoji('🇨🇳', 'Flag: China', "U+1F1E8 U+1F1F3"),
    Emoji('🇨🇴', 'Flag: Colombia', "U+1F1E8 U+1F1F4"),
    Emoji('🇨🇵', 'Flag: Clipperton Island', "U+1F1E8 U+1F1F5"),
    Emoji('🇨🇷', 'Flag: Costa Rica', "U+1F1E8 U+1F1F7"),
    Emoji('🇨🇺', 'Flag: Cuba', "U+1F1E8 U+1F1F8"),
    Emoji('🇨🇻', 'Flag: Cape Verde', "U+1F1E8 U+1F1FB"),
    Emoji('🇨🇼', 'Flag: Curaçao', "U+1F1E8 U+1F1FC"),
    Emoji('🇨🇽', 'Flag: Christmas Island', "U+1F1E8 U+1F1FD"),
    Emoji('🇨🇾', 'Flag: Cyprus', "U+1F1E8 U+1F1FE"),
    Emoji('🇨🇿', 'Flag: Czechia', "U+1F1E8 U+1F1FF"),
    Emoji('🇩🇪', 'Flag: Germany', "U+1F1E9 U+1F1EA"),
    Emoji('🇩🇬', 'Flag: Diego Garcia', "U+1F1E9 U+1F1EC"),
    Emoji('🇩🇯', 'Flag: Djibouti', "U+1F1E9 U+1F1EF"),
    Emoji('🇩🇰', 'Flag: Denmark', "U+1F1E9 U+1F1F0"),
    Emoji('🇩🇲', 'Flag: Dominica', "U+1F1E9 U+1F1F2"),
    Emoji('🇩🇴', 'Flag: Dominican Republic', "U+1F1E9 U+1F1F4"),
    Emoji('🇩🇿', 'Flag: Algeria', "U+1F1E9 U+1F1FF"),
    Emoji('🇪🇦', 'Flag: Ceuta & Melilla', "U+1F1EA U+1F1E6"),
    Emoji('🇪🇨', 'Flag: Ecuador', "U+1F1EA U+1F1E8"),
    Emoji('🇪🇪', 'Flag: Estonia', "U+1F1EA U+1F1EA"),
    Emoji('🇪🇬', 'Flag: Egypt', "U+1F1EA U+1F1EC"),
    Emoji('🇪🇭', 'Flag: Western Sahara', "U+1F1EA U+1F1ED"),
    Emoji('🇪🇷', 'Flag: Eritrea', "U+1F1EA U+1F1F7"),
    Emoji('🇪🇸', 'Flag: Spain', "U+1F1EA U+1F1F8"),
    Emoji('🇪🇹', 'Flag: Ethiopia', "U+1F1EA U+1F1F9"),
    Emoji('🇪🇺', 'Flag: European Union', "U+1F1EA U+1F1FA"),
    Emoji('🇫🇮', 'Flag: Finland', "U+1F1EB U+1F1EE"),
    Emoji('🇫🇯', 'Flag: Fiji', "U+1F1EB U+1F1F2"),
    Emoji('🇫🇰', 'Flag: Falkland Islands', "U+1F1EB U+1F1F0"),
    Emoji('🇫🇲', 'Flag: Micronesia', "U+1F1EB U+1F1F2"),
    Emoji('🇫🇴', 'Flag: Faroe Islands', "U+1F1EB U+1F1F4"),
    Emoji('🇫🇷', 'Flag: France', "U+1F1EB U+1F1F7"),
    Emoji('🇬🇦', 'Flag: Gabon', "U+1F1EC U+1F1E6"),
    Emoji('🇬🇧', 'Flag: United Kingdom', "U+1F1EC U+1F1E7"),
    Emoji('🇬🇩', 'Flag: Grenada', "U+1F1EC U+1F1E9"),
    Emoji('🇬🇪', 'Flag: Georgia', "U+1F1EC U+1F1EA"),
    Emoji('🇬🇫', 'Flag: French Guiana', "U+1F1EC U+1F1EB"),
    Emoji('🇬🇬', 'Flag: Guernsey', "U+1F1EC U+1F1EC"),
    Emoji('🇬🇭', 'Flag: Ghana', "U+1F1EC U+1F1ED"),
    Emoji('🇬🇮', 'Flag: Gibraltar', "U+1F1EC U+1F1EE"),
    Emoji('🇬🇱', 'Flag: Greenland', "U+1F1EC U+1F1F1"),
    Emoji('🇬🇲', 'Flag: Gambia', "U+1F1EC U+1F1F2"),
    Emoji('🇬🇳', 'Flag: Guinea', "U+1F1EC U+1F1F3"),
    Emoji('🇬🇵', 'Flag: Guadeloupe', "U+1F1EC U+1F1F5"),
    Emoji('🇬🇶', 'Flag: Equatorial Guinea', "U+1F1EC U+1F1F6"),
    Emoji('🇬🇷', 'Flag: Greece', "U+1F1EC U+1F1F7"),
    Emoji('🇬🇸', 'Flag: South Georgia & South Sandwich Islands',
        "U+1F1EC U+1F1F8"),
    Emoji('🇬🇹', 'Flag: Guatemala', "U+1F1EC U+1F1F9"),
    Emoji('🇬🇺', 'Flag: Guam', "U+1F1EC U+1F1FA"),
    Emoji('🇬🇼', 'Flag: Guinea-Bissau', "U+1F1EC U+1F1FC"),
    Emoji('🇬🇾', 'Flag: Guyana', "U+1F1EC U+1F1FE"),
    Emoji('🇭🇰', 'Flag: Hong Kong SAR China', "U+1F1ED U+1F1F0"),
    Emoji('🇭🇲', 'Flag: Heard & McDonald Islands', "U+1F1ED U+1F1F2"),
    Emoji('🇭🇳', 'Flag: Honduras', "U+1F1ED U+1F1F3"),
    Emoji('🇭🇷', 'Flag: Croatia', "U+1F1ED U+1F1F7"),
    Emoji('🇭🇹', 'Flag: Haiti', "U+1F1ED U+1F1F9"),
    Emoji('🇭🇺', 'Flag: Hungary', "U+1F1ED U+1F1FA"),
    Emoji('🇮🇨', 'Flag: Canary Islands', "U+1F1EE U+1F1E8"),
    Emoji('🇮🇩', 'Flag: Indonesia', "U+1F1EE U+1F1E9"),
    Emoji('🇮🇪', 'Flag: Ireland', "U+1F1EE U+1F1F0"),
    Emoji('🇮🇱', 'Flag: Israel', "U+1F1EE U+1F1F1"),
    Emoji('🇮🇲', 'Flag: Isle of Man', "U+1F1EE U+1F1F2"),
    Emoji('🇮🇳', 'Flag: India', "U+1F1EE U+1F1F3"),
    Emoji('🇮🇴', 'Flag: British Indian Ocean Territory', "U+1F1EE U+1F1F4"),
    Emoji('🇮🇶', 'Flag: Iraq', "U+1F1EE U+1F1F6"),
    Emoji('🇮🇷', 'Flag: Iran', "U+1F1EE U+1F1F7"),
    Emoji('🇮🇸', 'Flag: Iceland', "U+1F1EE U+1F1F8"),
    Emoji('🇮🇹', 'Flag: Italy', "U+1F1EE U+1F1F9"),
    Emoji('🇯🇪', 'Flag: Jersey', "U+1F1EF U+1F1EA"),
    Emoji('🇯🇲', 'Flag: Jamaica', "U+1F1EF U+1F1F2"),
    Emoji('🇯🇴', 'Flag: Jordan', "U+1F1EF U+1F1F4"),
    Emoji('🇯🇵', 'Flag: Japan', "U+1F1EF U+1F1F5"),
    Emoji('🇰🇪', 'Flag: Kenya', "U+1F1F0 U+1F1EA"),
    Emoji('🇰🇬', 'Flag: Kyrgyzstan', "U+1F1F0 U+1F1EC"),
    Emoji('🇰🇭', 'Flag: Cambodia', "U+1F1F0 U+1F1ED"),
    Emoji('🇰🇮', 'Flag: Kiribati', "U+1F1F0 U+1F1F7"),
    Emoji('🇰🇲', 'Flag: Comoros', "U+1F1F0 U+1F1F2"),
    Emoji('🇰🇳', 'Flag: St. Kitts & Nevis', "U+1F1F0 U+1F1F3"),
    Emoji('🇰🇵', 'Flag: North Korea', "U+1F1F0 U+1F1F5"),
    Emoji('🇰🇷', 'Flag: South Korea', "U+1F1F0 U+1F1F7"),
    Emoji('🇰🇼', 'Flag: Kuwait', "U+1F1F0 U+1F1FC"),
    Emoji('🇰🇾', 'Flag: Cayman Islands', "U+1F1F0 U+1F1FE"),
    Emoji('🇰🇿', 'Flag: Kazakhstan', "U+1F1F0 U+1F1FF"),
    Emoji('🇱🇦', 'Flag: Laos', "U+1F1F1 U+1F1E6"),
    Emoji('🇱🇧', 'Flag: Lebanon', "U+1F1F1 U+1F1E7"),
    Emoji('🇱🇨', 'Flag: St. Lucia', "U+1F1F1 U+1F1E8"),
    Emoji('🇱🇮', 'Flag: Liechtenstein', "U+1F1F1 U+1F1EE"),
    Emoji('🇱🇰', 'Flag: Sri Lanka', "U+1F1F1 U+1F1F0"),
    Emoji('🇱🇷', 'Flag: Liberia', "U+1F1F1 U+1F1F7"),
    Emoji('🇱🇸', 'Flag: Lesotho', "U+1F1F1 U+1F1F8"),
    Emoji('🇱🇹', 'Flag: Lithuania', "U+1F1F1 U+1F1F9"),
    Emoji('🇱🇺', 'Flag: Luxembourg', "U+1F1F1 U+1F1FA"),
    Emoji('🇱🇻', 'Flag: Latvia', "U+1F1F1 U+1F1FB"),
    Emoji('🇱🇾', 'Flag: Libya', "U+1F1F1 U+1F1FE"),
    Emoji('🇲🇦', 'Flag: Morocco', "U+1F1F2 U+1F1E6"),
    Emoji('🇲🇨', 'Flag: Monaco', "U+1F1F2 U+1F1E8"),
    Emoji('🇲🇩', 'Flag: Moldova', "U+1F1F2 U+1F1E9"),
    Emoji('🇲🇪', 'Flag: Montenegro', "U+1F1F2 U+1F1EA"),
    Emoji('🇲🇫', 'Flag: St. Martin', "U+1F1F2 U+1F1EB"),
    Emoji('🇲🇬', 'Flag: Madagascar', "U+1F1F2 U+1F1EC"),
    Emoji('🇲🇭', 'Flag: Marshall Islands', "U+1F1F2 U+1F1ED"),
    Emoji('🇲🇰', 'Flag: North Macedonia', "U+1F1F2 U+1F1F0"),
    Emoji('🇲🇱', 'Flag: Mali', "U+1F1F2 U+1F1F1"),
    Emoji('🇲🇲', 'Flag: Myanmar (Burma)', "U+1F1F2 U+1F1F2"),
    Emoji('🇲🇳', 'Flag: Mongolia', "U+1F1F2 U+1F1F3"),
    Emoji('🇲🇴', 'Flag: Macau Sar China', "U+1F1F2 U+1F1F4"),
    Emoji('🇲🇵', 'Flag: Northern Mariana Islands', "U+1F1F2 U+1F1F5"),
    Emoji('🇲🇶', 'Flag: Martinique', "U+1F1F2 U+1F1F6"),
    Emoji('🇲🇷', 'Flag: Mauritania', "U+1F1F2 U+1F1F7"),
    Emoji('🇲🇸', 'Flag: Montserrat', "U+1F1F2 U+1F1F8"),
    Emoji('🇲🇹', 'Flag: Malta', "U+1F1F2 U+1F1F9"),
    Emoji('🇲🇺', 'Flag: Mauritius', "U+1F1F2 U+1F1FA"),
    Emoji('🇲🇻', 'Flag: Maldives', "U+1F1F2 U+1F1FB"),
    Emoji('🇲🇼', 'Flag: Malawi', "U+1F1F2 U+1F1FC"),
    Emoji('🇲🇽', 'Flag: Mexico', "U+1F1F2 U+1F1F7"),
    Emoji('🇲🇾', 'Flag: Malaysia', "U+1F1F2 U+1F1F8"),
    Emoji('🇲🇿', 'Flag: Mozambique', "U+1F1F2 U+1F1FF"),
    Emoji('🇳🇦', 'Flag: Namibia', "U+1F1F3 U+1F1E6"),
    Emoji('🇳🇨', 'Flag: New Caledonia', "U+1F1F3 U+1F1E8"),
    Emoji('🇳🇪', 'Flag: Niger', "U+1F1F3 U+1F1EA"),
    Emoji('🇳🇫', 'Flag: Norfolk Island', "U+1F1F3 U+1F1EB"),
    Emoji('🇳🇬', 'Flag: Nigeria', "U+1F1F3 U+1F1EC"),
    Emoji('🇳🇮', 'Flag: Nicaragua', "U+1F1F3 U+1F1EE"),
    Emoji('🇳🇱', 'Flag: Netherlands', "U+1F1F3 U+1F1F1"),
    Emoji('🇳🇴', 'Flag: Norway', "U+1F1F3 U+1F1F4"),
    Emoji('🇳🇵', 'Flag: Nepal', "U+1F1F3 U+1F1F5"),
    Emoji('🇳🇷', 'Flag: Nauru', "U+1F1F3 U+1F1F7"),
    Emoji('🇳🇺', 'Flag: Niue', "U+1F1F3 U+1F1F8"),
    Emoji('🇳🇿', 'Flag: New Zealand', "U+1F1F3 U+1F1FF"),
    Emoji('🇴🇲', 'Flag: Oman', "U+1F1F4 U+1F1F2"),
    Emoji('🇵🇦', 'Flag: Panama', "U+1F1F5 U+1F1E6"),
    Emoji('🇵🇪', 'Flag: Peru', "U+1F1F5 U+1F1F7"),
    Emoji('🇵🇫', 'Flag: French Polynesia', "U+1F1F5 U+1F1EB"),
    Emoji('🇵🇬', 'Flag: Papua New Guinea', "U+1F1F5 U+1F1EC"),
    Emoji('🇵🇭', 'Flag: Philippines', "U+1F1F5 U+1F1ED"),
    Emoji('🇵🇰', 'Flag: Pakistan', "U+1F1F5 U+1F1F0"),
    Emoji('🇵🇱', 'Flag: Poland', "U+1F1F5 U+1F1F1"),
    Emoji('🇵🇲', 'Flag: St. Pierre & Miquelon', "U+1F1F5 U+1F1F2"),
    Emoji('🇵🇳', 'Flag: Pitcairn Islands', "U+1F1F5 U+1F1F3"),
    Emoji('🇵🇷', 'Flag: Puerto Rico', "U+1F1F5 U+1F1F7"),
    Emoji('🇵🇸', 'Flag: Palestinian Territories', "U+1F1F5 U+1F1F8"),
    Emoji('🇵🇹', 'Flag: Portugal', "U+1F1F5 U+1F1F9"),
    Emoji('🇵🇼', 'Flag: Palau', "U+1F1F5 U+1F1FC"),
    Emoji('🇵🇾', 'Flag: Paraguay', "U+1F1F5 U+1F1FE"),
    Emoji('🇶🇦', 'Flag: Qatar', "U+1F1F6 U+1F1E6"),
    Emoji('🇷🇪', 'Flag: Réunion', "U+1F1F7 U+1F1F8"),
    Emoji('🇷🇴', 'Flag: Romania', "U+1F1F7 U+1F1F4"),
    Emoji('🇷🇸', 'Flag: Serbia', "U+1F1F7 U+1F1F8"),
    Emoji('🇷🇺', 'Flag: Russia', "U+1F1F7 U+1F1FA"),
    Emoji('🇷🇼', 'Flag: Rwanda', "U+1F1F7 U+1F1FC"),
    Emoji('🇸🇦', 'Flag: Saudi Arabia', "U+1F1F8 U+1F1E6"),
    Emoji('🇸🇧', 'Flag: Solomon Islands', "U+1F1F8 U+1F1E7"),
    Emoji('🇸🇨', 'Flag: Seychelles', "U+1F1F8 U+1F1E8"),
    Emoji('🇸🇩', 'Flag: Sudan', "U+1F1F8 U+1F1E9"),
    Emoji('🇸🇪', 'Flag: Sweden', "U+1F1F8 U+1F1ED"),
    Emoji('🇸🇬', 'Flag: Singapore', "U+1F1F8 U+1F1F7"),
    Emoji('🇸🇭', 'Flag: St. Helena', "U+1F1F8 U+1F1ED"),
    Emoji('🇸🇮', 'Flag: Slovenia', "U+1F1F8 U+1F1EE"),
    Emoji('🇸🇯', 'Flag: Svalbard & Jan Mayen', "U+1F1F8 U+1F1EF"),
    Emoji('🇸🇰', 'Flag: Slovakia', "U+1F1F8 U+1F1F0"),
    Emoji('🇸🇱', 'Flag: Sierra Leone', "U+1F1F8 U+1F1F1"),
    Emoji('🇸🇲', 'Flag: San Marino', "U+1F1F8 U+1F1F2"),
    Emoji('🇸🇳', 'Flag: Senegal', "U+1F1F8 U+1F1F3"),
    Emoji('🇸🇴', 'Flag: Somalia', "U+1F1F8 U+1F1F4"),
    Emoji('🇸🇷', 'Flag: Suriname', "U+1F1F8 U+1F1F7"),
    Emoji('🇸🇸', 'Flag: South Sudan', "U+1F1F8 U+1F1F8"),
    Emoji('🇸🇹', 'Flag: São Tomé & Príncipe', "U+1F1F8 U+1F1F9"),
    Emoji('🇸🇻', 'Flag: El Salvador', "U+1F1F8 U+1F1FB"),
    Emoji('🇸🇽', 'Flag: Sint Maarten', "U+1F1F8 U+1F1FD"),
    Emoji('🇸🇾', 'Flag: Syria', "U+1F1F8 U+1F1FE"),
    Emoji('🇸🇿', 'Flag: Swaziland', "U+1F1F8 U+1F1FF"),
    Emoji('🇹🇦', 'Flag: Tristan Da Cunha', "U+1F1F9 U+1F1E6"),
    Emoji('🇹🇨', 'Flag: Turks & Caicos Islands', "U+1F1F9 U+1F1F0"),
    Emoji('🇹🇩', 'Flag: Chad', "U+1F1F9 U+1F1F2"),
    Emoji('🇹🇫', 'Flag: French Southern Territories', "U+1F1F9 U+1F1EB"),
    Emoji('🇹🇬', 'Flag: Togo', "U+1F1F9 U+1F1EC"),
    Emoji('🇹🇭', 'Flag: Thailand', "U+1F1F9 U+1F1ED"),
    Emoji('🇹🇯', 'Flag: Tajikistan', "U+1F1F9 U+1F1EF"),
    Emoji('🇹🇰', 'Flag: Tokelau', "U+1F1F9 U+1F1F0"),
    Emoji('🇹🇱', 'Flag: Timor-Leste', "U+1F1F9 U+1F1F1"),
    Emoji('🇹🇲', 'Flag: Turkmenistan', "U+1F1F9 U+1F1F2"),
    Emoji('🇹🇳', 'Flag: Tunisia', "U+1F1F9 U+1F1F3"),
    Emoji('🇹🇴', 'Flag: Tonga', "U+1F1F9 U+1F1F4"),
    Emoji('🇹🇷', 'Flag: Turkey', "U+1F1F9 U+1F1F7"),
    Emoji('🇹🇹', 'Flag: Trinidad & Tobago', "U+1F1F9 U+1F1F9"),
    Emoji('🇹🇻', 'Flag: Tuvalu', "U+1F1F9 U+1F1FB"),
    Emoji('🇹🇼', 'Flag: Taiwan', "U+1F1F9 U+1F1FC"),
    Emoji('🇹🇿', 'Flag: Tanzania', "U+1F1F9 U+1F1FF"),
    Emoji('🇺🇦', 'Flag: Ukraine', "U+1F1FA U+1F1E6"),
    Emoji('🇺🇬', 'Flag: Uganda', "U+1F1FA U+1F1EC"),
    Emoji('🇺🇲', 'Flag: U.S. Outlying Islands', "U+1F1FA U+1F1F2"),
    Emoji('🇺🇳', 'Flag: United Nations', "U+1F1FA U+1F1F3"),
    Emoji('🇺🇸', 'Flag: United States', "U+1F1FA U+1F1F8"),
    Emoji('🇺🇾', 'Flag: Uruguay', "U+1F1FA U+1F1F9"),
    Emoji('🇺🇿', 'Flag: Uzbekistan', "U+1F1FA U+1F1FF"),
    Emoji('🇻🇦', 'Flag: Vatican City', "U+1F1FB U+1F1E6"),
    Emoji('🇻🇨', 'Flag: St. Vincent & Grenadines', "U+1F1FB U+1F1E8"),
    Emoji('🇻🇪', 'Flag: Venezuela', "U+1F1FB U+1F1EA"),
    Emoji('🇻🇬', 'Flag: British Virgin Islands', "U+1F1FB U+1F1EC"),
    Emoji('🇻🇮', 'Flag: U.S. Virgin Islands', "U+1F1FB U+1F1EE"),
    Emoji('🇻🇳', 'Flag: Vietnam', "U+1F1FB U+1F1F3"),
    Emoji('🇻🇺', 'Flag: Vanuatu', "U+1F1FB U+1F1FA"),
    Emoji('🇼🇫', 'Flag: Wallis & Futuna', "U+1F1FC U+1F1EB"),
    Emoji('🇼🇸', 'Flag: Samoa', "U+1F1FC U+1F1F8"),
    Emoji('🇽🇰', 'Flag: Kosovo', "U+1F1FD U+1F1F0"),
    Emoji('🇾🇪', 'Flag: Yemen', "U+1F1FE U+1F1EA"),
    Emoji('🇾🇹', 'Flag: Mayotte', "U+1F1FE U+1F1F9"),
    Emoji('🇿🇦', 'Flag: South Africa', "U+1F1FF U+1F1E6"),
    Emoji('🇿🇲', 'Flag: Zambia', "U+1F1FF U+1F1F2"),
    Emoji('🇿🇼', 'Flag: Zimbabwe', "U+1F1FF U+1F1FC"),
  ]),
];
